"use client";

import { useEffect, useState } from "react";
import { englishCourse, englishUnits } from "./english-course-data";
import { canFinishLesson, readCell, scheduleReview, type ExerciseResult, type LearningCells, type ReviewState } from "./english-progress";
import { useEnglishProgress } from "./use-english-progress";
import { EnglishListen, EnglishRecorder } from "./english-audio";
import type { Lesson } from "./course-data";

type CourseLesson = typeof englishCourse[number];
type Save = (key: string, value: unknown) => void;
type Area = "today" | "course" | "review" | "words" | "materials" | "practice" | "progress";
const steps = ["Entender", "Ouvir e ler", "Praticar", "Produzir", "Concluir"];
const emptyResult: ExerciseResult = { answer: "", correct: false, assisted: false, attempts: 0 };

import { Exercise } from "./english-exercise";
import { EnglishDiagnostic, EnglishMaterials, EnglishPracticeHub, EnglishProgressPanel, EnglishWeek, WordTrainer } from "./english-tools-ui";
import { EnglishBook } from "./english-study-book";
import { lessonMinimumWords } from "./english-learning-tools";
function ExternalHelp({ lesson, draft }: { lesson: CourseLesson; draft: string }) {
  const [mode, setMode] = useState("explain");
  const [includeDraft, setIncludeDraft] = useState(false);
  const [message, setMessage] = useState("");
  const tasks: Record<string, string> = {
    explain: "Explique a ideia em português simples e dê três exemplos novos. Depois me faça uma pergunta de cada vez, espere minha resposta e explique meus erros sem entregar todas as respostas de início.",
    talk: "Faça uma conversa guiada em inglês sobre este tema, uma pergunta curta de cada vez. Espere minha resposta, sugira uma melhoria e continue. Use linguagem de iniciante. Ao final, resuma o que preciso praticar.",
    write: "Peça meu texto se eu ainda não o enviar. Analise clareza, uso da estrutura estudada e vocabulário. Mostre o trecho, uma sugestão e o motivo em português. Não reescreva tudo por mim: peça que eu faça uma nova versão. Não atribua nota ou nível oficial.",
    review: "Crie cinco atividades novas sobre o tema, uma por vez. Alterne completar frases, interpretar um texto curto e escrever uma frase. Espere minhas respostas, dê feedback explicado e termine com um roteiro de revisão."
  };
  const prompt = `Estou estudando inglês na Clareia. Aula ${lesson.number}: ${lesson.title}.\nObjetivo: ${lesson.goal}\nConteúdo estudado: ${lesson.content.concept}\n${tasks[mode]}\nUse dados fictícios; não peça informações pessoais. Considere que estou aprendendo sozinho. Se houver mais de uma resposta válida, explique. Sinalize suas incertezas.${includeDraft && draft ? `\nMeu rascunho, que escolhi compartilhar:\n${draft}` : ""}`;
  return <details className="en-external"><summary>Apoio fora da Clareia · opcional</summary><p>Não há IA integrada nem envio automático. Se quiser, copie a atividade, abra o chat gratuito que você já usa e cole lá. A aula pode ser concluída sem isso.</p><label className="en-field">O que quero praticar<select value={mode} onChange={(e) => { setMode(e.target.value); setMessage(""); }}><option value="explain">Entender melhor a explicação</option><option value="talk">Conversar sobre o tema</option><option value="write">Pedir sugestões para meu texto</option><option value="review">Receber mais exercícios</option></select></label>{draft && <label className="en-check"><input type="checkbox" checked={includeDraft} onChange={(e) => setIncludeDraft(e.target.checked)} />Incluir meu rascunho na mensagem que vou copiar</label>}<label className="en-field">Confira antes de copiar<textarea readOnly value={prompt} rows={7} onFocus={(e) => e.currentTarget.select()} /></label><div className="en-actions"><button type="button" onClick={async () => { try { await navigator.clipboard.writeText(prompt); setMessage("Mensagem copiada. Abra seu chat e cole quando quiser."); } catch { setMessage("Selecione a mensagem acima e copie manualmente."); } }}>Copiar atividade</button><a href="https://chatgpt.com/" target="_blank" rel="noopener noreferrer">Abrir ChatGPT ↗</a><a href="https://gemini.google.com/" target="_blank" rel="noopener noreferrer">Abrir Gemini ↗</a></div><small>Serviços externos podem exigir conta, ter limites gratuitos e cometer erros. Não compartilhe dados pessoais. Você também pode usar outro chat de sua preferência.</small>{message && <p role="status">{message}</p>}</details>;
}

function Classroom({ lesson, cells, save, onBack, onComplete, legacyDone }: { lesson: CourseLesson; cells: LearningCells; save: Save; onBack: () => void; onComplete: () => void; legacyDone: boolean }) {
  const prefix = lesson.id;
  const step = Math.max(0, Math.min(4, readCell<number>(cells, `${prefix}:step`, 0)));
  const draft = readCell<string>(cells, `${prefix}:draft`, "");
  const revision = readCell<string>(cells, `${prefix}:revision`, "");
  const checks = readCell<boolean[]>(cells, `${prefix}:checks`, [false, false, false]);
  const completed = readCell<boolean>(cells, `${prefix}:complete`, false);
  const words = readCell<string[]>(cells, `${prefix}:words`, []);
  const [transcript, setTranscript] = useState(false);
  const [transcriptUsed, setTranscriptUsed] = useState(false);
  const [translation, setTranslation] = useState(false);
  const [notice, setNotice] = useState("");
  const allQuestions = [...lesson.expansion.questions, lesson.expansion.transfer];
  const results = allQuestions.map((question) => readCell<ExerciseResult>(cells, `${prefix}:answer-${question.id}`, emptyResult));
  const ready = canFinishLesson(results, draft, checks, lessonMinimumWords(lesson.number));
  const answered = results.filter((r) => r.correct).length;
  function go(next: number) { window.speechSynthesis?.cancel(); save(`${prefix}:step`, next); }
  return <div className="en-classroom"><button className="en-back" type="button" onClick={onBack}>← Voltar à trilha</button><header className="en-class-header"><span className="en-kicker">AULA {String(lesson.number).padStart(2, "0")} · {englishUnits[Math.floor((lesson.number - 1) / 6)]}</span><h2>{lesson.title}</h2><p>{lesson.goal}</p><small>{lesson.duration} · faça no seu ritmo</small></header>
    {legacyDone && !completed && <p className="en-note">Você já concluiu esta aula na versão anterior. Esse histórico foi mantido; as novas atividades são um aprofundamento opcional.</p>}
    <nav className="en-steps" aria-label="Etapas da aula">{steps.map((label, index) => <button key={label} type="button" aria-current={step === index ? "step" : undefined} onClick={() => go(index)}><span>{index + 1}</span>{label}</button>)}</nav>
    <div className="en-panel" key={step}>
    {step === 0 && <><span className="en-kicker">ENTENDA A IDEIA</span><h3>{lesson.content.concept}</h3><p>{lesson.expansion.why}</p><div className="en-example"><span className="en-kicker">EXEMPLO COMENTADO</span><p>{lesson.expansion.simple}</p><p lang="en"><strong>{lesson.expansion.contrast[0]}</strong></p><p>{lesson.expansion.contrast[1]}</p></div><h3>Vocabulário para usar hoje</h3><div className="en-word-grid">{lesson.content.vocabulary.map((word) => <article key={word.english}><strong lang="en">{word.english}</strong><p>{word.portuguese}</p><button type="button" aria-pressed={words.includes(word.english)} onClick={() => save(`${prefix}:words`, words.includes(word.english) ? words.filter((w) => w !== word.english) : [...words, word.english])}>{words.includes(word.english) ? "✓ No meu caderno" : "+ Guardar expressão"}</button></article>)}</div><EnglishListen text={lesson.content.vocabulary.map((w) => w.english).join(". ")} label="Ouvir o vocabulário" /><h3>Observe estas frases</h3>{lesson.content.model.map((line) => <p lang="en" key={line}>{line}</p>)}<p className="en-hint">Foco na pronúncia: {lesson.expansion.pronunciation}</p></>}
    {step === 1 && <><span className="en-kicker">ESCUTA E COMPREENSÃO</span><h3>Primeiro ouça. Depois confira.</h3><p>Ouça o trecho e tente identificar o assunto e uma informação importante. Repita quantas vezes precisar. Sem voz disponível? Abra a transcrição e faça a atividade como leitura.</p><EnglishListen text={lesson.expansion.passage} label="Ouvir o trecho da aula" /><button type="button" aria-expanded={transcript} onClick={() => { setTranscript(!transcript); setTranscriptUsed(true); }}>{transcript ? "Ocultar transcrição" : "Mostrar transcrição / usar leitura"}</button>{transcript && <div className="en-example"><p lang="en">{lesson.expansion.passage}</p><button type="button" aria-expanded={translation} onClick={() => setTranslation(!translation)}>{translation ? "Ocultar tradução" : "Conferir tradução"}</button>{translation && <p>{lesson.expansion.translation}</p>}</div>}<Exercise exercise={lesson.expansion.questions.find((q) => q.id === "listen")!} stored={readCell<ExerciseResult | undefined>(cells, `${prefix}:answer-listen`, undefined)} assisted={transcriptUsed} onResult={(result) => save(`${prefix}:answer-listen`, result)} /><p className="en-note">Consultar o texto é um apoio válido. Este exercício não gera uma nota de compreensão oral.</p></>}
    {step === 2 && <><span className="en-kicker">PRÁTICA GUIADA</span><h3>Agora é sua vez</h3><p>Responda antes de abrir a dica. Se errar, leia o motivo e tente outra vez.</p><details><summary>Consultar o texto da aula</summary><p lang="en">{lesson.expansion.passage}</p></details>{lesson.expansion.questions.filter((q) => q.id !== "listen").map((question) => <Exercise key={question.id} exercise={question} stored={readCell<ExerciseResult | undefined>(cells, `${prefix}:answer-${question.id}`, undefined)} onResult={(result) => save(`${prefix}:answer-${question.id}`, result)} />)}<h3>Leve a estrutura para outro exemplo</h3><Exercise exercise={lesson.expansion.transfer} stored={readCell<ExerciseResult | undefined>(cells, `${prefix}:answer-transfer`, undefined)} onResult={(result) => save(`${prefix}:answer-transfer`, result)} /></>}
    {step === 3 && <><span className="en-kicker">ESCRITA E FALA</span><h3>Use o inglês para dizer algo seu</h3><p>{lesson.expansion.writingStart}</p><ul>{lesson.content.practice.map((item) => <li key={item}>{item}</li>)}</ul><label className="en-field">Meu rascunho em inglês<textarea lang="en" rows={7} value={draft} maxLength={3500} onChange={(e) => save(`${prefix}:draft`, e.target.value)} placeholder="Escreva aqui. Você pode inventar nomes e situações." /></label><small>{draft.trim() ? draft.trim().split(/\s+/).length : 0} palavras · salvamento automático · limite de 3.500 caracteres</small><h4>Confira você mesmo</h4><p>A lista orienta a revisão. Não há correção automática de texto livre.</p>{lesson.expansion.checklist.map((item, index) => <label className="en-check" key={item}><input type="checkbox" checked={!!checks[index]} onChange={(e) => save(`${prefix}:checks`, checks.map((check, i) => i === index ? e.target.checked : check))} />{item}</label>)}<details><summary>Escrever uma segunda versão (opcional)</summary><label className="en-field">Meu texto revisado<textarea lang="en" rows={5} value={revision} maxLength={3500} onChange={(e) => save(`${prefix}:revision`, e.target.value)} /></label></details><EnglishRecorder lessonId={prefix} /><ExternalHelp lesson={lesson} draft={draft} /></>}
    {step === 4 && <><span className="en-kicker">FECHAR O CICLO</span><h3>{completed ? "Aula registrada. Continue praticando!" : "O que você praticou hoje"}</h3><p>{lesson.result}</p><ul className="en-completion-list"><li>{answered === 4 ? "✓" : "○"} {answered}/4 exercícios resolvidos corretamente — com ou sem apoio</li><li>{draft.trim().split(/\s+/).length >= lessonMinimumWords(lesson.number) ? "✓" : "○"} Rascunho com pelo menos {lessonMinimumWords(lesson.number)} palavras</li><li>{checks.every(Boolean) ? "✓" : "○"} Autoavaliação: {checks.filter(Boolean).length}/3 itens conferidos</li></ul><p className="en-note">Concluir significa realizar as atividades. Não é certificado de nível, fluência nem avaliação automática da sua escrita ou fala.</p><div className="en-actions"><button type="button" className="en-primary" disabled={!ready || completed} onClick={() => { save(`${prefix}:complete`, true); save(`${prefix}:review`, scheduleReview(null, true)); onComplete(); setNotice("Aula concluída. A primeira revisão fica para amanhã."); }}>{completed ? "✓ Aula concluída" : "Concluir e programar revisão"}</button><button type="button" onClick={() => go(answered < 4 ? 2 : 3)}>Voltar à prática</button></div>{notice && <p role="status">{notice}</p>}<ExternalHelp lesson={lesson} draft={draft} /></>}
    <footer className="en-step-footer"><button type="button" disabled={step === 0} onClick={() => go(step - 1)}>← Anterior</button><span>{step + 1} de {steps.length}</span>{step < 4 ? <button type="button" className="en-primary" onClick={() => go(step + 1)}>Próxima etapa →</button> : <button type="button" onClick={onBack}>Ver trilha →</button>}</footer></div>
  </div>;
}

function ReviewCard({ lesson, previous, save }: { lesson: CourseLesson; previous: ReviewState; save: Save }) {
  const [result, setResult] = useState<ExerciseResult>();
  const [saved, setSaved] = useState(false);
  return <article className="en-panel"><span className="en-kicker">REVISÃO · AULA {lesson.number}</span><h3>{lesson.title}</h3><p>Tente lembrar sem consultar a aula. A questão retoma o que você já praticou; acertar não mede fluência.</p><Exercise exercise={lesson.expansion.transfer} stored={result} onResult={setResult} /><div className="en-actions"><button type="button" className="en-primary" disabled={!result?.correct || saved} onClick={() => { save(`${lesson.id}:review`, scheduleReview(previous, !!result?.correct && !result.assisted)); setSaved(true); }}>Registrar revisão</button></div>{saved && <p role="status">Revisão registrada. A próxima data está na sua lista.</p>}<small>Intervalos: 1, 3, 7, 14 e 30 dias. Usar apoio reinicia o intervalo em 1 dia. Antecipar revisões não acelera a sequência.</small></article>;
}

export default function EnglishWorkspace({ uid, legacyProgress, onComplete }: { uid: string; legacyProgress: Record<string, string>; onComplete: (lesson: Lesson) => void }) {
  const { cells, ready, status, save, retry } = useEnglishProgress(uid);
  const [area, setArea] = useState<Area>("today");
  const [lessonId, setLessonId] = useState<string | null>(null);
  const [reviewId, setReviewId] = useState<string | null>(null);
  const [search, setSearch] = useState("");
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    const refresh = () => setNow(Date.now());
    const timer = setInterval(refresh, 60_000);
    window.addEventListener("focus", refresh);
    return () => { clearInterval(timer); window.removeEventListener("focus", refresh); };
  }, []);
  const preferences = readCell<{ minutes: number; goal: string }>(cells, "preferences", { minutes: 15, goal: "Cotidiano" });
  const done = englishCourse.filter((lesson) => readCell(cells, `${lesson.id}:complete`, false));
  const reviews = englishCourse.flatMap((lesson) => { const state = readCell<ReviewState | null>(cells, `${lesson.id}:review`, null); return state ? [{ lesson, state }] : []; }).sort((a, b) => a.state.due - b.state.due);
  const due = reviews.filter((item) => item.state.due <= now);
  const nextLesson = englishCourse.find((lesson) => cells[`${lesson.id}:step`] && !readCell(cells, `${lesson.id}:complete`, false)) ?? englishCourse.find((lesson) => !readCell(cells, `${lesson.id}:complete`, false) && legacyProgress[lesson.id] !== "done") ?? englishCourse.find((lesson) => !readCell(cells, `${lesson.id}:complete`, false)) ?? englishCourse[0];
  const selected = englishCourse.find((lesson) => lesson.id === lessonId);
  const selectedReview = reviews.find((review) => review.lesson.id === reviewId);
  const savedWords = englishCourse.flatMap((lesson) => lesson.content.vocabulary.filter((word) => readCell<string[]>(cells, `${lesson.id}:words`, []).includes(word.english)).map((word) => ({ ...word, lesson })));
  function openLesson(id: string) { window.speechSynthesis?.cancel(); if (!cells[`${id}:step`]) save(`${id}:step`, 0); setLessonId(id); setReviewId(null); }
  if (!ready) return <div className="page-content"><p role="status">Carregando suas aulas de inglês…</p></div>;
  return <div className="page-content en-workspace"><div className="en-sync"><span role="status">{status}</span><button type="button" onClick={retry}>Sincronizar</button></div>
    {selected ? <Classroom key={selected.id} lesson={selected} cells={cells} save={save} legacyDone={legacyProgress[selected.id] === "done"} onBack={() => setLessonId(null)} onComplete={() => onComplete(selected)} /> : <>
    <section className="en-hero"><div><span className="en-kicker">CLAREIA · INGLÊS NA PRÁTICA</span><h2>Um pouco hoje.<br />Mais confiança amanhã.</h2><p>Entenda, escute, pratique e use o inglês. Sua trilha para estudar com autonomia, uma aula de cada vez.</p><button className="en-primary" type="button" onClick={() => openLesson(nextLesson.id)}>{cells[`${nextLesson.id}:step`] ? "Retomar" : "Começar"} aula {nextLesson.number} →</button></div><div className="en-hero-stat"><strong>{done.length}<span>/{englishCourse.length}</span></strong><p>aulas da nova trilha concluídas</p><progress max={englishCourse.length} value={done.length} aria-label="Aulas concluídas na nova trilha" /><small>O histórico anterior continua preservado.</small></div></section>
    <nav className="en-nav" aria-label="Área de inglês">{([{ id: "today", label: "Meu dia" }, { id: "course", label: "Trilha de aulas" }, { id: "practice", label: "Laboratório" }, { id: "progress", label: "Meu progresso" }, { id: "review", label: `Revisão${due.length ? ` (${due.length})` : ""}` }, { id: "words", label: "Meu caderno" }, { id: "materials", label: "Materiais gratuitos" }] as { id: Area; label: string }[]).map((tab) => <button type="button" key={tab.id} aria-current={area === tab.id ? "page" : undefined} onClick={() => { setArea(tab.id); setReviewId(null); }}>{tab.label}</button>)}</nav>
    {area === "today" && <><div className="en-two-col"><section className="en-panel"><span className="en-kicker">SEU PRÓXIMO PASSO</span><h3>{nextLesson.title}</h3><p>{nextLesson.goal}</p><div className="en-actions"><button className="en-primary" type="button" onClick={() => openLesson(nextLesson.id)}>Abrir minha aula →</button>{due.length > 0 && <button type="button" onClick={() => setArea("review")}>{due.length} revisão(ões) para hoje</button>}</div><p className="en-note">Não precisa terminar tudo de uma vez. A etapa e o rascunho ficam guardados.</p></section><section className="en-panel"><span className="en-kicker">UMA ROTINA POSSÍVEL</span><h3>O inglês cabe no seu dia</h3><label className="en-field">Tempo por sessão<select value={preferences.minutes} onChange={(e) => save("preferences", { ...preferences, minutes: Number(e.target.value) })}><option value={10}>10 minutos</option><option value={15}>15 minutos</option><option value={25}>25 minutos</option></select></label><label className="en-field">Meu objetivo<select value={preferences.goal} onChange={(e) => save("preferences", { ...preferences, goal: e.target.value })}><option>Cotidiano</option><option>Leitura para o ENEM</option><option>Viagens e trabalho</option></select></label><p>{preferences.minutes === 10 ? "2 min de revisão + 5 min de uma etapa + 3 min criando frases." : preferences.minutes === 15 ? "3 min de revisão + 8 min de aula + 4 min de produção." : "5 min de revisão + 12 min de aula + 8 min de escrita ou fala."}</p><small>Objetivo: {preferences.goal}. {preferences.goal === "Leitura para o ENEM" ? "Dê atenção às aulas 19, 37, 38 e 43–47, sem pular os fundamentos." : preferences.goal === "Viagens e trabalho" ? "Retome pedidos (10), direções (17), conversação (21), compromissos (36) e e-mails (40)." : "Pratique suas apresentações, sua rotina e conversas simples."} Isso orienta seu estudo; não é um teste de nível.</small></section></div><section className="en-panel"><h3>Aprender sem professor: como usar</h3><ol><li>Leia a explicação e observe os exemplos.</li><li>Escute, consulte o texto quando precisar e repita uma frase.</li><li>Responda, leia o feedback e corrija o que errou.</li><li>Escreva algo seu e use a lista para revisar.</li><li>Volte nos dias de revisão. Se quiser ajuda extra, copie a atividade para um chat externo.</li></ol><p className="en-note">48 aulas, dos fundamentos à leitura crítica, com laboratórios para continuar praticando. Concluir a trilha não equivale a certificação de fluência.</p></section><EnglishWeek cells={cells} save={save} openLesson={openLesson} /><details className="en-panel"><summary>Descobrir por onde começar</summary><EnglishDiagnostic cells={cells} save={save} openLesson={openLesson} /></details></>}
    {area === "course" && <section><div className="en-section-heading"><div><span className="en-kicker">48 AULAS · OITO UNIDADES</span><h3>Sua trilha de aprendizagem</h3></div><label className="en-field">Buscar aula<input type="search" placeholder="Rotina, leitura, passado…" value={search} onChange={(e) => setSearch(e.target.value)} /></label></div>{englishUnits.map((unit, index) => { const unitLessons = englishCourse.slice(index * 6, index * 6 + 6).filter((lesson) => `${lesson.title} ${lesson.goal}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))); return unitLessons.length ? <section className="en-unit" key={unit}><h3><span>0{index + 1}</span> {unit}</h3><div className="en-lesson-grid">{unitLessons.map((lesson) => { const complete = readCell(cells, `${lesson.id}:complete`, false); return <article className="en-lesson-card" key={lesson.id}><span className="en-kicker">AULA {String(lesson.number).padStart(2, "0")} · {complete ? "CONCLUÍDA" : legacyProgress[lesson.id] === "done" ? "HISTÓRICO PRESERVADO" : cells[`${lesson.id}:step`] ? "EM ANDAMENTO" : "PARA COMEÇAR"}</span><h4>{lesson.title}</h4><p>{lesson.goal}</p><button type="button" onClick={() => openLesson(lesson.id)}>{complete ? "Rever aula" : "Abrir aula"} →</button></article>; })}</div></section> : null; })}{!englishCourse.some((lesson) => `${lesson.title} ${lesson.goal}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR"))) && <p className="en-panel">Nenhuma aula encontrada. Tente outra palavra.</p>}</section>}
    {area === "review" && <section><span className="en-kicker">LEMBRAR TAMBÉM É APRENDER</span><h3>Suas revisões</h3>{selectedReview ? <><button type="button" className="en-back" onClick={() => setReviewId(null)}>← Ver revisões</button><ReviewCard key={selectedReview.lesson.id} lesson={selectedReview.lesson} previous={selectedReview.state} save={save} /></> : !reviews.length ? <div className="en-panel"><h4>Sua primeira revisão começa com uma aula.</h4><p>Ao concluir as novas atividades, a Clareia agenda uma revisão para o dia seguinte.</p><button type="button" onClick={() => openLesson(nextLesson.id)}>Abrir aula {nextLesson.number}</button></div> : <><p>{due.length ? `${due.length} revisão(ões) disponível(is) para hoje.` : "Tudo em dia! Veja quando voltar. Você também pode revisar antes."}</p><div className="en-lesson-grid">{reviews.map(({ lesson, state }) => <article className="en-lesson-card" key={lesson.id}><span className="en-kicker">{state.due <= now ? "REVISAR HOJE" : `PRÓXIMA: ${new Date(state.due).toLocaleDateString("pt-BR")}`}</span><h4>{lesson.title}</h4><button type="button" onClick={() => setReviewId(lesson.id)}>Praticar de memória →</button></article>)}</div></>}</section>}
    {area === "words" && <section><span className="en-kicker">VOCABULÁRIO EM CONTEXTO</span><h3>Meu caderno de expressões</h3><WordTrainer cells={cells} save={save} /><p>Antes de revelar, tente lembrar o sentido e criar uma frase com a expressão.</p>{!savedWords.length ? <div className="en-panel"><p>Seu caderno ainda está vazio. Abra uma aula e toque em “Guardar expressão”.</p><button type="button" onClick={() => setArea("course")}>Explorar aulas</button></div> : <div className="en-word-grid">{savedWords.map((word) => <article key={`${word.lesson.id}:${word.english}`}><span className="en-kicker">AULA {word.lesson.number}</span><h4 lang="en">{word.english}</h4><details><summary>Revelar significado</summary><p>{word.portuguese}</p></details><div className="en-actions"><button type="button" onClick={() => openLesson(word.lesson.id)}>Ver no contexto</button><button type="button" onClick={() => save(`${word.lesson.id}:words`, readCell<string[]>(cells, `${word.lesson.id}:words`, []).filter((value) => value !== word.english))}>Remover</button></div></article>)}</div>}</section>}
    {area === "materials" && <><EnglishMaterials /><EnglishBook cells={cells} /></>}
    {area === "practice" && <EnglishPracticeHub cells={cells} save={save} openLesson={openLesson} />}
    {area === "progress" && <EnglishProgressPanel cells={cells} save={save} openLesson={openLesson} />}
    </>}
  </div>;
}
