import { lessons } from "./course-data";
import { englishLessonContent } from "./english-lesson-content";
import { extendedEnglishCourse } from "./english-extended-data";

export type EnglishExercise = {
  id: string;
  skill: "Estrutura" | "Vocabulário" | "Escuta" | "Leitura";
  prompt: string;
  answers: string[];
  options?: string[];
  hint: string;
  explanation: string;
};
export type EnglishExpansion = {
  why: string;
  simple: string;
  contrast: [string, string];
  pronunciation: string;
  passage: string;
  translation: string;
  questions: EnglishExercise[];
  transfer: EnglishExercise;
  writingStart: string;
  checklist: string[];
};
const choice = (id: string, skill: EnglishExercise["skill"], prompt: string, options: string[], answer: string, hint: string, explanation: string): EnglishExercise => ({ id, skill, prompt, options, answers: [answer], hint, explanation });
const fill = (prompt: string, answers: string[], hint: string, explanation: string): EnglishExercise => ({ id: "write", skill: "Estrutura", prompt, answers, hint, explanation });
const listen = (prompt: string, options: string[], answer: string, explanation: string) => choice("listen", "Escuta", prompt, options, answer, "Ouça novamente. Procure a parte que responde à pergunta; você pode consultar a transcrição.", explanation);

// Conteúdo original Clareia. IDs antigos são preservados; não equivalem a certificação CEFR.
export const englishExpansion: Record<string, EnglishExpansion> = {
  "english-01": {
    why: "Em inglês, geralmente precisamos mostrar quem faz ou é alguma coisa. Em vez de começar apenas com 'am', diga 'I am'. Para nome, use 'My name is'; para moradia, 'I live in'. Você pode usar dados fictícios em todos os exercícios.",
    simple: "Pense em blocos: I am + quem sou; I live in + cidade. Aprenda o bloco inteiro antes de trocar a informação final.",
    contrast: ["I am a student. → Eu sou estudante.", "I live in Recife. → Eu moro em Recife."],
    pronunciation: "Ouça 'I'm', a forma curta de 'I am'. As duas formas são corretas; a contração é comum na fala.",
    passage: "Hello! My name is Leo. I am a student. I live in Recife. I like music.",
    translation: "Olá! Meu nome é Leo. Sou estudante. Moro em Recife. Gosto de música.",
    questions: [choice("choose", "Estrutura", "Como dizer 'Sou estudante'?", ["I have student.", "I am a student.", "I live student."], "I am a student.", "Para dizer quem você é, use I am.", "I am expressa 'eu sou'. Antes de uma profissão ou papel no singular, aqui usamos a: a student."), fill("Complete com uma palavra: I live ___ Recife.", ["in"], "Qual palavra liga live a uma cidade?", "Live in + cidade: I live in Recife."), listen("Em qual cidade Leo mora?", ["Recife", "São Paulo", "London"], "Recife", "Ele diz 'I live in Recife'. Não é necessário entender cada palavra para localizar a cidade.")],
    transfer: choice("transfer", "Estrutura", "Nina quer dizer 'Meu nome é Nina'. Qual frase funciona?", ["My name are Nina.", "I name Nina.", "My name is Nina."], "My name is Nina.", "Name é singular.", "O bloco é My name is + nome."), writingStart: "Hello! My name is…", checklist: ["Usei My name is para o nome.", "Usei I am para dizer quem sou.", "Escrevi uma frase com I live in."]
  },
  "english-02": {
    why: "To be muda de forma conforme o sujeito: I am; he, she e it is; you, we e they are. Não escolha pelo número de pessoas no português: you are serve tanto para você quanto para vocês. O adjetivo não muda: she is happy, they are happy.", simple: "Primeiro encontre o sujeito. Depois escolha am, is ou are. Só então acrescente a informação.", contrast: ["She is happy. → Ela está feliz.", "They are happy. → Eles estão felizes."], pronunciation: "Compare 'she is' e 'she's'. Ao ouvir a forma curta, o verbo continua presente.", passage: "I am at school. My sister is at home. We are students. Our teacher is very kind.", translation: "Estou na escola. Minha irmã está em casa. Somos estudantes. Nosso professor é muito gentil.",
    questions: [choice("choose", "Estrutura", "Complete: They ___ students.", ["am", "are", "is"], "are", "They usa a mesma forma de we.", "They combina com are: They are students."), fill("Complete: My sister ___ at home.", ["is"], "My sister pode ser substituído por she.", "Um sujeito singular como my sister usa is."), listen("Onde está a irmã?", ["At work", "At school", "At home"], "At home", "A fala diz 'My sister is at home'.")], transfer: choice("transfer", "Estrutura", "Qual frase está correta?", ["You is ready.", "You are ready.", "You am ready."], "You are ready.", "You sempre usa are no presente de to be.", "Mesmo para uma única pessoa: You are ready."), writingStart: "I am… My friend is… We are…", checklist: ["Conferi o sujeito de cada frase.", "Usei am, is e are com os sujeitos certos.", "Não acrescentei outro verbo sem necessidade."]
  },
  "english-03": {
    why: "Com to be, a negativa coloca not depois do verbo; a pergunta troca a ordem do sujeito e do verbo. Não use do nesse caso: Are you ready?, e não Do you are ready? Em respostas curtas afirmativas, diga Yes, I am, não Yes, I'm.", simple: "Afirmação: you are. Negativa: you are not. Pergunta: are you?", contrast: ["She is at school. → Ela está na escola.", "Is she at school? → Ela está na escola?"], pronunciation: "Ouça isn't e aren't. Uma palavra curta pode mudar a frase para negativa; preste atenção ao contexto.", passage: "Are you ready? Yes, I am. Is your brother at school? No, he isn't. He is at home today.", translation: "Você está pronto? Sim. Seu irmão está na escola? Não. Ele está em casa hoje.",
    questions: [choice("choose", "Estrutura", "Transforme 'They are tired' em pergunta.", ["Do they are tired?", "They tired are?", "Are they tired?"], "Are they tired?", "Traga are para antes de they.", "Perguntas com to be invertem a ordem: Are they tired?"), fill("Complete: No, he ___ . Use a forma negativa curta de is.", ["isn't", "isn’t"], "Junte is e not.", "Is not pode virar isn't. O apóstrofo marca a contração."), listen("O irmão está na escola?", ["Sim", "Não, está em casa", "Não foi informado"], "Não, está em casa", "No, he isn't nega; He is at home confirma onde ele está.")], transfer: choice("transfer", "Estrutura", "Resposta curta afirmativa para 'Are you a student?'", ["Yes, I'm.", "Yes, I am.", "Yes, I do."], "Yes, I am.", "Responda com o verbo que apareceu na pergunta.", "A resposta termina com am, sem contração: Yes, I am."), writingStart: "I am not… Are you…?", checklist: ["Coloquei not depois de to be nas negativas.", "Inverti verbo e sujeito nas perguntas.", "Usei respostas curtas completas."]
  },
  "english-04": {
    why: "Comece dizendo hora e minuto: six ten, seven thirty. Use at para um horário e on para um dia: at eight, on Monday. Em 1 p.m., p.m. já indica a parte do dia; não escreva 13 p.m. Preços podem ser ditos com número e moeda.", simple: "Para começar, leia os números do relógio: 8:15 = eight fifteen. Não precisa aprender todas as formas de horário ao mesmo tempo.", contrast: ["At seven thirty → às sete e meia.", "On Monday → na segunda-feira."], pronunciation: "Treine thirteen e thirty ouvindo a sílaba forte: são números diferentes. Confirme um número importante repetindo-o.", passage: "The English class starts at seven thirty on Monday. The book costs fifteen dollars. The next class is on Friday.", translation: "A aula de inglês começa às sete e meia na segunda. O livro custa quinze dólares. A próxima aula é na sexta.",
    questions: [choice("choose", "Vocabulário", "Qual horário corresponde a seven thirty?", ["7:13", "7:30", "3:07"], "7:30", "Thirty é trinta.", "Seven thirty = sete horas e trinta minutos."), fill("Complete: The class starts ___ eight.", ["at"], "Use a preposição de um horário exato.", "At eight indica às oito horas."), listen("Quanto custa o livro?", ["Fifty dollars", "Fifteen dollars", "Five dollars"], "Fifteen dollars", "A fala usa fifteen, quinze, não fifty, cinquenta.")], transfer: choice("transfer", "Estrutura", "Como representar 13:00 no formato de 12 horas?", ["13 p.m.", "1 a.m.", "1 p.m."], "1 p.m.", "Depois do meio-dia, o relógio de 12 horas volta ao 1.", "13:00 equivale a 1 p.m. Não misture 13 com p.m."), writingStart: "My class starts at… on…", checklist: ["Usei at antes dos horários.", "Usei on antes dos dias da semana.", "Não misturei horário de 24 horas com a.m./p.m."]
  },
  "english-05": {
    why: "Use o presente simples para hábitos. Com I, you, we e they, use work, study, go. Com he, she e it: works, studies, goes. Em study, consoante + y vira -ies. Na afirmativa, não coloque am antes de work: I work, não I am work.", simple: "Comece com sua rotina: I wake up, I study, I work. Ao falar de outra pessoa, verifique se o verbo precisa mudar.", contrast: ["I study in the morning. → Eu estudo de manhã.", "She studies in the morning. → Ela estuda de manhã."], pronunciation: "Ouça a diferença entre work e works. O som final tem função: indica a forma usada com he/she/it.", passage: "I wake up at six. I have breakfast at six thirty. I go to school in the morning. My sister works in the afternoon. At night, we watch a show.", translation: "Acordo às seis. Tomo café às seis e meia. Vou à escola de manhã. Minha irmã trabalha à tarde. À noite, assistimos a um programa.",
    questions: [choice("choose", "Estrutura", "Escolha a frase correta sobre um hábito dela.", ["She study every day.", "She studies every day.", "She is study every day."], "She studies every day.", "Study termina em consoante + y.", "Com she, study vira studies. Não usamos is antes do verbo nessa construção."), fill("Complete: I go ___ school in the morning.", ["to"], "Aprenda o bloco go to school.", "Para ir à escola, use go to school; go for school não expressa esse hábito."), listen("Quando a irmã trabalha?", ["In the morning", "At night", "In the afternoon"], "In the afternoon", "My sister works in the afternoon = minha irmã trabalha à tarde.")], transfer: choice("transfer", "Estrutura", "Agora fale de Leo: 'I go to bed at ten.'", ["Leo go to bed at ten.", "Leo goes to bed at ten.", "Leo is go to bed at ten."], "Leo goes to bed at ten.", "Leo pode ser substituído por he.", "Go vira goes com he/she/it: Leo goes to bed at ten."), writingStart: "I wake up at…\nI have breakfast…\nI go to school…", checklist: ["Escrevi seis frases sobre hábitos.", "Usei go to school e horários consistentes.", "Conferi -s/-es/-ies quando falei de he ou she."]
  },
  "english-06": {
    why: "Do e does ajudam a formar perguntas sobre hábitos. Does já carrega a marca da terceira pessoa, então o verbo seguinte fica na base: Does she work? Na negativa: I don't work; she doesn't work. Com to be, continue usando Are you?, não Do you are?.", simple: "Use does com he/she/it. Depois de does ou doesn't, tire o -s do verbo principal.", contrast: ["She works here. → Ela trabalha aqui.", "Does she work here? → Ela trabalha aqui?"], pronunciation: "Em uma pergunta natural, do you pode soar bem ligado. Ouça a frase inteira, sem exigir pausas entre todas as palavras.", passage: "Do you study at night? No, I don't. I study in the morning. Does your sister work? Yes, she does. She works at a shop.", translation: "Você estuda à noite? Não. Estudo de manhã. Sua irmã trabalha? Sim. Ela trabalha em uma loja.", questions: [choice("choose", "Estrutura", "Qual pergunta está correta?", ["Does he likes music?", "Does he like music?", "Do he like music?"], "Does he like music?", "Does já marca a terceira pessoa.", "Depois de does, usamos like, sem -s."), fill("Complete: She ___ work on Sunday. Use a contração de does not.", ["doesn't", "doesn’t"], "Junte does + not.", "She doesn't work: a negativa tem doesn't e o verbo base."), listen("A pessoa estuda à noite?", ["Sim", "Não, estuda de manhã", "Não estuda"], "Não, estuda de manhã", "No, I don't responde à pergunta sobre a noite. A frase seguinte informa a manhã.")], transfer: choice("transfer", "Estrutura", "Complete: Where ___ Ana live?", ["is", "do", "does"], "does", "Ana é uma pessoa, equivalente a she.", "Where does Ana live? usa does + sujeito + verbo base."), writingStart: "Do you…?\nDoes your friend…?", checklist: ["Escolhi do ou does conforme o sujeito.", "Usei verbo base depois de does.", "Respondi às perguntas com do/does ou don't/doesn't."]
  },
  "english-07": {
    why: "My, your, his, her, its, our e their vêm antes de um substantivo. A escolha depende de quem possui, não do gênero da coisa em português. Para Ana, her brother; para Leo, his sister. Our é nosso/nossa; their é deles/delas.", simple: "Pergunte 'de quem?'. De Ana: her. De Leo: his. De nós: our. Depois coloque a coisa ou pessoa relacionada.", contrast: ["His sister → a irmã dele.", "Her brother → o irmão dela."], pronunciation: "Ouça our em uma frase inteira, como our family. A forma de falar varia entre sotaques.", passage: "This is Ana. Her brother is Pedro. Their parents live in Brazil. Pedro has a sister. His sister likes music.", translation: "Esta é Ana. O irmão dela é Pedro. Os pais deles moram no Brasil. Pedro tem uma irmã. A irmã dele gosta de música.", questions: [choice("choose", "Estrutura", "O irmão da Ana: ___ brother.", ["His", "Her", "Our"], "Her", "O possuidor é Ana.", "Her refere-se à Ana, mesmo quando o substantivo é brother."), fill("Complete: We love ___ family.", ["our"], "A família é de nós.", "We é sujeito; our é possessivo antes de family."), listen("Quem é o irmão de Ana?", ["Pedro", "Leo", "Não foi informado"], "Pedro", "Her brother is Pedro apresenta a relação familiar.")], transfer: choice("transfer", "Estrutura", "Leo mostra a mãe dele. Ele diz:", ["This is my mother.", "This is I mother.", "This is me mother."], "This is my mother.", "Antes de mother, use o possessivo de I.", "My mother indica minha mãe. I e me não substituem my aqui."), writingStart: "This is… Their family…", checklist: ["Usei possessivos antes de substantivos.", "Escolhi his/her por quem possui.", "Usei informações fictícias ou sem dados sensíveis."]
  },
  "english-08": {
    why: "There is apresenta algo singular; there are apresenta plural. A e an significam um/uma: a book, an apple. A escolha de a/an depende do som seguinte. Some costuma aparecer em afirmações e any em perguntas/negativas de quantidade indefinida, mas isso não é uma regra sem exceções.", simple: "Primeiro conte: uma coisa → there is; mais de uma → there are.", contrast: ["There is a book. → Há um livro.", "There are some books. → Há alguns livros."], pronunciation: "Em there is, as palavras se ligam. Ouça a frase inteira antes de repeti-la.", passage: "There is a desk in my room. There are two books on the desk. There isn't a television. There is an orange bag next to the chair.", translation: "Há uma mesa no meu quarto. Há dois livros sobre ela. Não há televisão. Há uma bolsa laranja ao lado da cadeira.", questions: [choice("choose", "Estrutura", "Complete: There ___ two chairs.", ["is", "am", "are"], "are", "Two chairs é plural.", "There are apresenta duas ou mais coisas."), fill("Complete: There is ___ apple. Use a ou an.", ["an"], "Apple começa com som de vogal.", "Usamos an apple pelo som inicial de apple."), listen("O que não há no quarto?", ["A desk", "A television", "Books"], "A television", "There isn't a television nega a existência de uma televisão.")], transfer: choice("transfer", "Estrutura", "Como perguntar se há livros?", ["Is there any books?", "Are there any books?", "There are any books?"], "Are there any books?", "Books é plural; inverta are e there.", "Are there any books? pergunta sobre uma quantidade indefinida de livros."), writingStart: "There is…\nThere are…", checklist: ["Diferenciei singular e plural.", "Incluí uma negativa.", "Usei a/an antes de substantivos singulares quando necessário."]
  },
  "english-09": {
    why: "Can não recebe -s: she can. O verbo seguinte vem sem to: can swim. Para negar, use cannot ou can't. Para perguntar, leve can para antes do sujeito. Use essas frases para habilidades, pedidos e possibilidades simples.", simple: "Can + verbo base funciona com todos os sujeitos. Não escreva cans ou can to.", contrast: ["She can swim. → Ela sabe nadar.", "Can she swim? → Ela sabe nadar?"], pronunciation: "Can e can't podem ser difíceis de distinguir. Ouça o contexto e não julgue apenas um som final isolado.", passage: "I can cook, but I can't drive. My friend can drive. Can you help me with dinner? Yes, I can.", translation: "Sei cozinhar, mas não sei dirigir. Meu amigo sabe dirigir. Você pode me ajudar com o jantar? Sim.", questions: [choice("choose", "Estrutura", "Qual frase expressa uma habilidade?", ["She cans swim.", "She can to swim.", "She can swim."], "She can swim.", "Can não muda e não exige to.", "Can + swim: o verbo principal fica na forma base."), fill("Complete: ___ you help me?", ["can"], "Comece com o verbo de possibilidade/habilidade desta aula.", "Can you help me? é um pedido de ajuda."), listen("O que a pessoa não sabe fazer?", ["Cook", "Drive", "Help with dinner"], "Drive", "I can't drive indica a habilidade que falta.")], transfer: choice("transfer", "Estrutura", "Negue 'They can sing'.", ["They don't can sing.", "They can't sing.", "They can not to sing."], "They can't sing.", "Não use do com can.", "A negativa é can't/cannot + verbo base."), writingStart: "I can… but I can't…", checklist: ["Usei can sem -s.", "Usei verbo base sem to depois de can.", "Incluí uma habilidade, uma dificuldade e um pedido."]
  },
  "english-10": {
    why: "I would like, ou I'd like, expressa um pedido ou desejo educado. Could I have…? também funciona em pedidos. Para encerrar, use That's all, thank you. Em um restaurante, aprenda expressões inteiras e pratique substituindo apenas o alimento.", simple: "Escolha um bloco: I'd like + item + please. Depois treine ouvir a resposta.", contrast: ["I'd like some water, please. → Gostaria de água, por favor.", "Anything else? → Mais alguma coisa?"], pronunciation: "I'd é a contração de I would. Ouça a frase completa para reconhecer o pedido.", passage: "Good afternoon. Could I have a sandwich, please? Of course. Anything else? I'd like some water. That's all, thank you.", translation: "Boa tarde. Poderia pedir um sanduíche, por favor? Claro. Mais alguma coisa? Gostaria de água. É só, obrigado.", questions: [choice("choose", "Vocabulário", "O atendente pergunta 'Anything else?'. Ele quer saber:", ["Seu nome", "Se deseja mais alguma coisa", "Onde você mora"], "Se deseja mais alguma coisa", "Else significa algo além do que já foi pedido.", "Anything else? confirma se o pedido terminou."), fill("Complete: I'd ___ some water, please.", ["like"], "A expressão completa é I would like.", "I'd like = I would like. É um pedido educado."), listen("Qual bebida foi pedida?", ["Coffee", "Juice", "Water"], "Water", "I'd like some water identifica a bebida.")], transfer: choice("transfer", "Vocabulário", "Como encerrar o pedido educadamente?", ["That's all, thank you.", "Where do you live?", "I'm a student."], "That's all, thank you.", "Mostre que não deseja mais itens.", "That's all encerra o pedido; thank you agradece."), writingStart: "Customer: Could I have…?\nServer: …", checklist: ["Escrevi as falas dos dois personagens.", "Usei please e thank you.", "Incluí uma pergunta e o encerramento do pedido."]
  },
  "english-11": {
    why: "Was/were são o passado de to be. I, he, she e it usam was; you, we e they usam were. Para negar: wasn't/weren't. Para perguntar: Was she…? ou Were they…? Não acrescente did antes de was/were.", simple: "Troque am/is por was e are por were quando falar de uma situação passada.", contrast: ["She is tired today. → Ela está cansada hoje.", "She was tired yesterday. → Ela estava cansada ontem."], pronunciation: "Ouça was em uma frase natural. A pronúncia pode mudar conforme o destaque dado à palavra.", passage: "Yesterday was busy. I was at school in the morning. My friends were there too. We were tired, but the class was interesting.", translation: "Ontem foi corrido. Eu estava na escola de manhã. Meus amigos também estavam lá. Estávamos cansados, mas a aula foi interessante.", questions: [choice("choose", "Estrutura", "Complete: We ___ at home yesterday.", ["was", "were", "is"], "were", "We usa o passado de are.", "We were é a forma correta do passado de to be."), fill("Complete: She ___ happy yesterday.", ["was"], "She usa was no passado.", "She was happy descreve um estado passado."), listen("Como estava a turma?", ["Tired", "Angry", "Lost"], "Tired", "We were tired informa o estado da turma.")], transfer: choice("transfer", "Estrutura", "Pergunta correta no passado:", ["Did you were at home?", "Were you at home?", "Was you at home?"], "Were you at home?", "Com you, use were; coloque antes do sujeito.", "Were you at home? usa to be sem did."), writingStart: "Yesterday, I was… My friends were…", checklist: ["Usei uma expressão de tempo passado.", "Escolhi was/were pelo sujeito.", "Não usei did junto de was/were."]
  },
  "english-12": {
    why: "Verbos regulares recebem -ed, mas há ajustes: live → lived; study → studied. A forma passada é igual para todos os sujeitos. Em perguntas e negativas, did/didn't já marca o passado: Did you study?, não Did you studied?.", simple: "Afirmação: studied. Pergunta: did + study. Negativa: didn't + study.", contrast: ["She watched a film. → Ela assistiu a um filme.", "She didn't watch a film. → Ela não assistiu a um filme."], pronunciation: "-ed não tem sempre o mesmo som: worked termina em /t/, played em /d/ e wanted tem uma sílaba extra /ɪd/. Treine com modelos.", passage: "Yesterday, I studied English and cleaned my room. My brother played a game. We didn't watch television. We finished our homework.", translation: "Ontem estudei inglês e limpei meu quarto. Meu irmão jogou. Não assistimos à televisão. Terminamos a lição de casa.", questions: [choice("choose", "Estrutura", "Escolha a pergunta correta.", ["Did she studied?", "Does she studied?", "Did she study?"], "Did she study?", "Depois de did, use o verbo base.", "Did marca o passado; study não recebe -ed na pergunta."), fill("Escreva o passado de study.", ["studied"], "Consoante + y muda para -ied.", "Study → studied. Compare play → played: antes de y há uma vogal."), listen("O que eles NÃO fizeram?", ["Homework", "Watch television", "Study English"], "Watch television", "We didn't watch television é a frase negativa.")], transfer: choice("transfer", "Estrutura", "Negue 'I worked yesterday'.", ["I didn't worked yesterday.", "I didn't work yesterday.", "I don't worked yesterday."], "I didn't work yesterday.", "Use didn't e o verbo base.", "O passado fica em didn't. Work permanece sem -ed."), writingStart: "Yesterday, I… Then, I…", checklist: ["Usei passado em ações concluídas.", "Conferi a grafia de -ed.", "Usei verbo base depois de did/didn't."]
  },
  "english-13": {
    why: "Verbos irregulares não seguem a regra de -ed: go/went, have/had, do/did, make/made, get/got, see/saw. Aprenda em frases e revise depois. Perguntas e negativas continuam usando did + verbo base, inclusive com esses verbos.", simple: "Na afirmação, use o passado irregular. Depois de did ou didn't, volte ao verbo original.", contrast: ["She went home. → Ela foi para casa.", "Did she go home? → Ela foi para casa?"], pronunciation: "Ouça went e want como palavras diferentes. Não presuma a pronúncia apenas pela escrita.", passage: "Yesterday, I went to the park. I saw my friend there. We had lunch and made a plan for the weekend. I got home at five.", translation: "Ontem fui ao parque. Vi meu amigo lá. Almoçamos e fizemos um plano para o fim de semana. Cheguei em casa às cinco.", questions: [choice("choose", "Estrutura", "Qual é o passado de see?", ["Seed", "Saw", "Seen"], "Saw", "O par aprendido aqui é see/saw.", "No past simple, use saw. Seen aparece em outras estruturas, não substitui saw nessa afirmação."), fill("Complete: Did she ___ to school? Use go ou went.", ["go"], "Did já marca o passado.", "Did she go? usa a forma base go."), listen("Onde a pessoa encontrou o amigo?", ["At school", "At the park", "At a shop"], "At the park", "A pessoa foi ao parque e diz que viu o amigo 'there', lá.")], transfer: choice("transfer", "Estrutura", "Passado de 'We have lunch together':", ["We haved lunch together.", "We had lunch together.", "We has lunch together."], "We had lunch together.", "Have tem passado irregular.", "Have → had, para todos os sujeitos no past simple."), writingStart: "I went… I saw… We had…", checklist: ["Usei verbos irregulares em contexto.", "Não inventei formas com -ed.", "Voltei ao verbo base depois de did."]
  },
  "english-14": {
    why: "Para planos, combine sujeito + am/is/are + going to + verbo base. Cada parte tem função. Não esqueça to nem o verbo to be: She is going to study. Na pergunta, inverta is e she. Na negativa, acrescente not depois de is.", simple: "Pense em três peças: I am | going to | study. Troque só o sujeito e a ação quando necessário.", contrast: ["We study every day. → Estudamos todos os dias.", "We are going to study tonight. → Vamos estudar hoje à noite."], pronunciation: "Você pode ouvir gonna em conversas informais. Nesta etapa, pratique a forma completa going to e reconheça a redução sem precisar usá-la.", passage: "This weekend, I am going to visit my family. My sister is going to study. We are going to cook together on Sunday.", translation: "Neste fim de semana, vou visitar minha família. Minha irmã vai estudar. Vamos cozinhar juntos no domingo.", questions: [choice("choose", "Estrutura", "Qual frase expressa um plano corretamente?", ["She going to study.", "She is going study.", "She is going to study."], "She is going to study.", "Precisamos de is e to.", "A estrutura é is + going to + study."), fill("Complete: We ___ going to travel.", ["are"], "We usa are.", "We are going to travel mantém todas as peças da estrutura."), listen("O que farão juntos no domingo?", ["Travel", "Cook", "Study"], "Cook", "We are going to cook together on Sunday expressa o plano conjunto.")], transfer: choice("transfer", "Estrutura", "Como perguntar sobre o plano deles?", ["Are they going to study?", "Do they going to study?", "They are going study?"], "Are they going to study?", "A pergunta começa com are.", "Inverta are e they, mantendo going to study."), writingStart: "Next week, I am going to…", checklist: ["Escrevi planos concretos.", "Mantive am/is/are e going to.", "Usei verbo base depois de to."]
  },
  "english-15": {
    why: "Para comparar duas coisas, muitos adjetivos curtos usam -er + than: cheaper than. Longos costumam usar more: more interesting than. Há grafias especiais, como big/bigger, e irregulares: good/better, bad/worse. Não junte more com better.", simple: "Escolha a forma comparativa e depois use than para apresentar a outra coisa.", contrast: ["This phone is cheaper than that one.", "This book is more interesting than that one."], pronunciation: "Ouça o comparativo junto de than. A comparação é um bloco de significado, não só uma palavra isolada.", passage: "My new phone is cheaper than my old one. The screen is bigger. The camera is better, but the battery is worse.", translation: "Meu celular novo é mais barato que o antigo. A tela é maior. A câmera é melhor, mas a bateria é pior.", questions: [choice("choose", "Estrutura", "Comparativo correto de good:", ["Gooder", "More better", "Better"], "Better", "Good tem uma forma irregular.", "Good → better. More better repete a comparação indevidamente."), fill("Complete: A car is faster ___ a bicycle.", ["than"], "Qual palavra introduz o segundo elemento da comparação?", "Faster than = mais rápido que."), listen("Qual parte do novo celular é pior?", ["The camera", "The battery", "The screen"], "The battery", "The battery is worse indica a desvantagem.")], transfer: choice("transfer", "Estrutura", "Compare usando interesting.", ["This course is interestinger.", "This course is more interesting.", "This course is more interestinger."], "This course is more interesting.", "Interesting é um adjetivo longo.", "Usamos more interesting, não interestinger."), writingStart: "This… is… than…", checklist: ["Comparei duas opções.", "Usei than quando citei a segunda opção.", "Não escrevi more better ou more cheaper."]
  },
  "english-16": {
    why: "As preposições descrevem relações: in = dentro; on = sobre uma superfície; under = embaixo; next to = ao lado; between = entre; behind = atrás; in front of = na frente. Uma tradução isolada não serve para todos os contextos; aqui estamos falando de lugar.", simple: "Imagine dois objetos. Qual é a posição de um em relação ao outro? Escolha a expressão para essa relação.", contrast: ["The key is in the box. → A chave está dentro da caixa.", "The key is on the box. → A chave está sobre a caixa."], pronunciation: "Treine next to como um bloco. Há vários sons consonantais próximos; comece devagar e volte ao ritmo natural.", passage: "The book is on the desk. The bag is under the chair. The phone is in the bag. The chair is next to the window.", translation: "O livro está sobre a mesa. A bolsa está embaixo da cadeira. O celular está na bolsa. A cadeira está ao lado da janela.", questions: [choice("choose", "Vocabulário", "Qual expressão significa 'ao lado de'?", ["Under", "Next to", "Behind"], "Next to", "São duas palavras nesta expressão.", "Next to indica uma posição ao lado."), fill("Complete: The key is ___ the box. A chave está dentro da caixa.", ["in"], "Pense no interior da caixa.", "In the box indica dentro da caixa."), listen("Onde está o celular?", ["On the desk", "Next to the window", "In the bag"], "In the bag", "The phone is in the bag identifica a localização.")], transfer: choice("transfer", "Vocabulário", "The cat is behind the sofa. Onde está o gato?", ["Sobre o sofá", "Atrás do sofá", "Dentro do sofá"], "Atrás do sofá", "Behind expressa uma posição posterior.", "Behind the sofa = atrás do sofá."), writingStart: "The… is…\nThere is…", checklist: ["Descrevi posições de objetos.", "Usei pelo menos três preposições.", "Conferi se a descrição combina com o lugar imaginado."]
  },
  "english-17": {
    why: "Para dar direções, use ações no imperativo: go, turn, cross. Não é necessário dizer you em cada instrução. Para pedir informação de modo educado, comece com Excuse me. On your left/right descreve o lado de quem está seguindo o trajeto.", simple: "Monte um caminho com ações em ordem: go straight, turn left, cross the street.", contrast: ["Turn left. → Vire à esquerda.", "It's on your left. → Fica à sua esquerda."], pronunciation: "Ouça left e right em instruções curtas. Repita uma direção para confirmar quando não tiver certeza.", passage: "Excuse me. How do I get to the library? Go straight for two blocks. Turn right at the bank. The library is on your left.", translation: "Com licença. Como chego à biblioteca? Siga em frente por dois quarteirões. Vire à direita no banco. A biblioteca fica à sua esquerda.", questions: [choice("choose", "Vocabulário", "O que significa go straight?", ["Vire à esquerda", "Siga em frente", "Pare aqui"], "Siga em frente", "É seguir sem virar.", "Go straight indica continuar em frente."), fill("Complete: Turn ___. Vire à esquerda.", ["left"], "O contrário de right nessa direção.", "Turn left = vire à esquerda."), listen("Em qual lugar é preciso virar à direita?", ["At the library", "At the school", "At the bank"], "At the bank", "Turn right at the bank usa o banco como referência.")], transfer: choice("transfer", "Vocabulário", "Como pedir direções educadamente?", ["Excuse me. How do I get to the station?", "I am the station.", "I have a station."], "Excuse me. How do I get to the station?", "Use How do I get to…?", "A pergunta pede o caminho; Excuse me chama a atenção com educação."), writingStart: "Excuse me. How do I get to…?\nGo…", checklist: ["Escrevi instruções em ordem.", "Diferenciei turn left de on your left.", "Usei um lugar fictício, sem divulgar endereço pessoal."]
  },
  "english-18": {
    why: "Para ações acontecendo agora, use am/is/are + verbo-ing. Não basta colocar -ing sozinho. Algumas grafias mudam: make/making, run/running. Compare com o presente simples de hábitos. Nem todo verbo costuma aparecer no contínuo: para gostar, prefira I like.", simple: "Hábito: I study every day. Agora: I am studying. O verbo to be faz parte da segunda estrutura.", contrast: ["She works every day. → Ela trabalha todos os dias.", "She is working now. → Ela está trabalhando agora."], pronunciation: "Ouça a terminação -ing. Não acrescente uma sílaba extra depois do som final.", passage: "It is Saturday. I am studying English now. My brother is cooking. My parents are watching a film. We usually visit our family on Saturdays.", translation: "É sábado. Estou estudando inglês agora. Meu irmão está cozinhando. Meus pais estão assistindo a um filme. Costumamos visitar nossa família aos sábados.", questions: [choice("choose", "Estrutura", "O que está acontecendo agora?", ["She studying now.", "She is studying now.", "She study now."], "She is studying now.", "Use is + verbo-ing.", "She is studying tem o auxiliar e a forma -ing."), fill("Complete: They ___ watching a film now.", ["are"], "They combina com are.", "They are watching descreve uma ação em andamento."), listen("O que o irmão está fazendo?", ["Cooking", "Studying", "Watching a film"], "Cooking", "My brother is cooking é a informação sobre o irmão.")], transfer: choice("transfer", "Estrutura", "Qual frase descreve hábito, não ação atual?", ["I am studying right now.", "I study every morning.", "I am cooking now."], "I study every morning.", "Procure a expressão de repetição.", "Every morning indica rotina; usamos study no presente simples."), writingStart: "Right now, I am… Usually, I…", checklist: ["Usei to be + -ing nas ações atuais.", "Incluí uma frase de hábito para comparar.", "Conferi o sujeito e a forma de to be."]
  },
  "english-19": {
    why: "Antes de traduzir, identifique o gênero e o objetivo do texto. Skimming busca a ideia geral; scanning localiza uma informação específica. Uma alternativa correta precisa de evidência: uma palavra parecida sozinha não basta. Inferir é ligar pistas, não inventar informação.", simple: "Pergunte: quem escreveu, para quem e para quê? Depois procure o trecho que responde à questão.", contrast: ["Ideia geral: do que o texto trata?", "Detalhe: qual horário ou nome o texto informa?"], pronunciation: "Leia uma frase curta em voz alta depois de entender seu sentido; leitura e fala podem se apoiar.", passage: "Community notice. The library opens at nine on Saturday. Students can borrow books for free. Bring your student card. The library is closed on Sunday.", translation: "Aviso comunitário. A biblioteca abre às nove no sábado. Estudantes podem pegar livros emprestados gratuitamente. Traga sua carteira de estudante. A biblioteca fecha no domingo.", questions: [choice("choose", "Leitura", "O texto desta aula tem como principal objetivo:", ["Contar uma história de ficção", "Informar sobre o uso da biblioteca", "Vender um celular"], "Informar sobre o uso da biblioteca", "Observe o título Community notice e as instruções.", "Horário, empréstimo e documento necessário indicam um aviso informativo."), fill("Segundo o texto, ela abre às ___ no sábado. Responda em inglês por extenso.", ["nine"], "Procure opens at.", "The library opens at nine contém a informação solicitada."), listen("O que o estudante deve levar?", ["Money", "A student card", "A phone"], "A student card", "Bring your student card informa o documento necessário.")], transfer: choice("transfer", "Leitura", "Novo aviso: 'Free entry on Fridays.' O que é possível concluir?", ["A entrada é gratuita às sextas", "O lugar só abre às sextas", "Tudo vendido lá é gratuito"], "A entrada é gratuita às sextas", "Limite a conclusão ao que está escrito.", "Entry é entrada. A frase não informa os outros dias nem o preço de produtos."), writingStart: "Escreva em inglês: The text is a… It informs readers about… The evidence is… Você pode explicar o raciocínio em português depois.", checklist: ["Identifiquei o objetivo do texto.", "Justifiquei minha resposta com um trecho.", "Não acrescentei fatos que o texto não informa."]
  },
  "english-20": {
    why: "Ouvir não é reconhecer todas as palavras de uma vez. Na primeira tentativa, procure o assunto; na segunda, detalhes; depois confira a transcrição. Separe o que ouviu com certeza do que imaginou. Consultar a transcrição é apoio, não motivo para abandonar a atividade.", simple: "Primeiro: sobre o quê? Depois: quem, onde e quando? Só então confira o texto.", contrast: ["Ideia geral: alguém combinando um encontro.", "Detalhes: local, horário e mudança de plano."], pronunciation: "Falas naturais ligam palavras. Não espere uma pausa entre cada uma; ouça expressões inteiras.", passage: "Hi, Ana. Let's meet at the library tomorrow. It opens at nine, but I can arrive at ten. Please bring your English book. We can study together.", translation: "Oi, Ana. Vamos nos encontrar na biblioteca amanhã. Ela abre às nove, mas posso chegar às dez. Por favor, traga seu livro de inglês. Podemos estudar juntos.", questions: [choice("choose", "Escuta", "Qual é o objetivo principal da mensagem?", ["Comprar um livro", "Combinar um encontro para estudar", "Cancelar uma viagem"], "Combinar um encontro para estudar", "Preste atenção em let's meet e study together.", "A pessoa propõe um encontro na biblioteca para estudar."), fill("A pessoa consegue chegar às ___. Responda em inglês por extenso.", ["ten"], "O horário de abertura e o de chegada são diferentes.", "I can arrive at ten informa a chegada; nine é a abertura."), listen("O que Ana deve levar?", ["An English book", "Food", "A laptop"], "An English book", "Please bring your English book é o pedido.")], transfer: choice("transfer", "Escuta", "Ao ouvir um horário, você ficou em dúvida. O que fazer?", ["Marcar qualquer número e seguir", "Reouvir o trecho e conferir o contexto", "Concluir que não entende inglês"], "Reouvir o trecho e conferir o contexto", "Busque confirmar uma informação específica.", "Reouvir com uma pergunta em mente ajuda a separar detalhes parecidos."), writingStart: "Assunto principal:…\nEntendi com certeza:…\nPrecisei conferir:…", checklist: ["Ouvi antes de revelar a transcrição, se o áudio estava disponível.", "Distingui horário de abertura e chegada.", "Anotei uma dificuldade específica para revisar."]
  },
  "english-21": {
    why: "Conversar inclui responder e devolver uma pergunta. Comece com uma frase que você entende, acrescente um detalhe e use How about you? Se não entender, peça repetição. Não precisa responder rápido antes de conseguir responder com sentido.", simple: "Resposta + detalhe + pergunta de volta. Se travar, peça tempo ou repetição.", contrast: ["I like music. → Resposta curta.", "I like music. I play the guitar. How about you? → Resposta que mantém a conversa."], pronunciation: "Use pausas para organizar a fala. Fluência não significa falar o mais rápido possível.", passage: "What do you do? I'm a student. I study in the morning. What do you like? I like music and technology. How about you? I like sports.", translation: "O que você faz? Sou estudante. Estudo de manhã. Do que você gosta? Gosto de música e tecnologia. E você? Gosto de esportes.", questions: [choice("choose", "Vocabulário", "Como pedir para a pessoa repetir?", ["Could you repeat that, please?", "I repeat you.", "What time is it?"], "Could you repeat that, please?", "Use um pedido educado com repeat.", "Could you repeat that, please? permite esclarecer sem encerrar a conversa."), fill("Complete: How ___ you? (E você?)", ["about"], "O bloco aprendido é How about you?", "How about you? devolve a pergunta ao interlocutor."), listen("Quando o estudante estuda?", ["At night", "In the morning", "In the afternoon"], "In the morning", "I study in the morning acrescenta um detalhe à apresentação.")], transfer: choice("transfer", "Vocabulário", "Qual resposta mantém a conversa?", ["Music.", "I like music. How about you?", "Yes."], "I like music. How about you?", "Responda e convide a outra pessoa a falar.", "A frase informa uma preferência e devolve uma pergunta."), writingStart: "A: What do you like?\nB: …\nA: …", checklist: ["Respondi e acrescentei um detalhe.", "Fiz uma pergunta de volta.", "Incluí uma forma educada de pedir ajuda."]
  },
  "english-22": {
    why: "Interfaces costumam usar verbos no imperativo: open, save, update. Primeiro identifique a ação e depois o objeto: save changes = salvar alterações. Failed indica falha; completed indica conclusão. Nunca compartilhe senhas, códigos ou chaves de acesso ao pedir ajuda.", simple: "Ache o verbo: open, save, try. Ele mostra o que a interface pede que você faça.", contrast: ["Save changes. → Salve as alterações.", "The update failed. → A atualização falhou."], pronunciation: "Treine sign in e sign out em frases. A segunda palavra muda a ação.", passage: "Sign in to continue. Open settings and save changes. The update failed. Check your connection and try again. Do not share your password.", translation: "Entre para continuar. Abra as configurações e salve as alterações. A atualização falhou. Verifique sua conexão e tente novamente. Não compartilhe sua senha.", questions: [choice("choose", "Vocabulário", "O que significa save changes?", ["Apagar a conta", "Salvar alterações", "Abrir a câmera"], "Salvar alterações", "Save é salvar; changes são alterações.", "O comando salva as mudanças feitas."), fill("Complete: Try ___. (Tente novamente.)", ["again"], "A palavra significa de novo.", "Try again é um comando comum depois de uma falha."), listen("O que não deve ser compartilhado?", ["A book", "A password", "A public lesson"], "A password", "Do not share your password orienta a proteger a senha.")], transfer: choice("transfer", "Leitura", "'Upload completed successfully' indica:", ["Envio concluído com sucesso", "Envio ainda não começou", "Senha incorreta"], "Envio concluído com sucesso", "Procure completed e successfully.", "A mensagem confirma conclusão, não uma falha."), writingStart: "Sign in =…\nSettings =…\nSave changes =…", checklist: ["Identifiquei ações em mensagens de interface.", "Distingui sucesso de falha.", "Não incluí senhas ou dados privados no glossário."]
  },
  "english-23": {
    why: "Escolha a estrutura pelo significado: hábito, ação em andamento, ação concluída ou plano. Expressões de tempo ajudam, mas não decidem tudo sozinhas. Today pode aparecer em diferentes tempos, conforme o contexto. Pergunte primeiro o que você quer comunicar.", simple: "Hábito: study. Agora: am studying. Ontem: studied. Plano: am going to study.", contrast: ["I study every day. → Hábito.", "I am studying right now. → Ação em andamento."], pronunciation: "Ao falar, destaque a informação que diferencia as frases: yesterday, now, tomorrow. Não dependa apenas de uma terminação curta.", passage: "I study English every day. Yesterday, I watched a short video. Right now, I am writing a message. Tomorrow, I am going to practise speaking.", translation: "Estudo inglês todos os dias. Ontem assisti a um vídeo curto. Agora estou escrevendo uma mensagem. Amanhã vou praticar fala.", questions: [choice("choose", "Estrutura", "Qual frase expressa uma ação concluída ontem?", ["I study yesterday.", "I studied yesterday.", "I am study yesterday."], "I studied yesterday.", "Use past simple para essa ação concluída.", "Studied é o passado regular de study."), fill("Complete: Right now, she ___ studying.", ["is"], "O contínuo precisa de to be.", "She is studying descreve a ação em andamento."), listen("O que a pessoa vai praticar amanhã?", ["Reading", "Speaking", "Cooking"], "Speaking", "Tomorrow, I am going to practise speaking expressa o plano.")], transfer: choice("transfer", "Estrutura", "Qual frase fala de um plano?", ["We were at school.", "We study every day.", "We are going to study tonight."], "We are going to study tonight.", "Procure going to.", "Are going to study apresenta o plano para hoje à noite."), writingStart: "Every day, I…\nYesterday, I…\nRight now, I…\nTomorrow, I…", checklist: ["Escrevi hábito, passado, ação atual e plano.", "Conferi os auxiliares de cada estrutura.", "Escolhi o tempo pelo significado, não por uma palavra isolada."]
  },
  "english-24": {
    why: "Uma apresentação tem começo, desenvolvimento e encerramento. Organize quem você é, sua rotina, uma experiência e um plano. Use conectivos que domina: and, but, because, then. Revise uma coisa por vez: clareza, ordem, verbos e pronúncia.", simple: "Monte quatro blocos curtos. Fale com palavras que você entende e dê um exemplo em cada bloco.", contrast: ["I like technology. → Informação.", "I like technology because I enjoy building things. → Informação com motivo."], pronunciation: "Marque pausas entre os quatro blocos. Grave duas versões e compare se a segunda ficou mais fácil de acompanhar, não se ficou sem sotaque.", passage: "Hello, I'm Jo. I am a student and I like technology. I study in the morning. Last year, I started learning English. Next year, I am going to build a website. Thank you for listening.", translation: "Olá, sou Jo. Sou estudante e gosto de tecnologia. Estudo de manhã. No ano passado comecei a aprender inglês. No ano que vem vou construir um site. Obrigado por ouvir.", questions: [choice("choose", "Estrutura", "Qual expressão introduz um motivo?", ["Because", "Yesterday", "Next to"], "Because", "Ela responde a 'por quê?'.", "Because conecta uma informação ao seu motivo."), fill("Complete o encerramento: Thank you for ___ . Use o verbo listen na forma adequada.", ["listening"], "Depois de for, aqui usamos a forma -ing.", "Thank you for listening = obrigado por ouvir."), listen("Qual é o plano de Jo para o próximo ano?", ["Buy a car", "Build a website", "Move abroad"], "Build a website", "I am going to build a website informa o plano.")], transfer: choice("transfer", "Leitura", "Qual sequência organiza melhor a apresentação?", ["Nome → rotina → experiência → plano", "Palavras aleatórias sem conexão", "Apenas uma lista de verbos"], "Nome → rotina → experiência → plano", "Pense nos quatro blocos da aula.", "Essa sequência ajuda quem ouve a acompanhar as ideias."), writingStart: "Hello…\nUsually…\nLast year…\nIn the future…", checklist: ["Organizei 12 a 15 frases em quatro blocos.", "Usei palavras que consigo explicar.", "Revisei clareza, tempos verbais e encerramento."]
  }
};

export const englishCourse = [...lessons.filter(lesson => lesson.subject === "english").map(lesson => ({ ...lesson, content: englishLessonContent[lesson.id], expansion: englishExpansion[lesson.id] })), ...extendedEnglishCourse];
export const englishUnits = ["Primeiros passos", "Inglês do cotidiano", "Experiências e planos", "Leitura e autonomia", "Ampliar a comunicação", "Narrativas e possibilidades", "Textos para a vida real", "Leitura crítica e projeto"];
export const englishResources = [
  { title: "British Council · Teens", url: "https://learnenglishteens.britishcouncil.org/skills", level: "Por nível", focus: "Leitura, escuta, escrita e fala", task: "Escolha uma atividade do seu nível. Tente antes de consultar o texto ou gabarito. Depois anote três expressões e faça uma frase com cada uma." },
  { title: "VOA · Let's Learn English 1", url: "https://learningenglish.voanews.com/p/5644.html", level: "Iniciantes", focus: "Vídeos e inglês americano", task: "Comece pela Lesson 1. Veja o vídeo para entender a situação; repita com apoio do texto e pratique duas falas do diálogo." },
  { title: "British Council · LearnEnglish", url: "https://learnenglish.britishcouncil.org/free-resources", level: "Por nível", focus: "Gramática, vocabulário e situações reais", task: "Filtre pelo assunto que está estudando. Faça uma atividade gratuita e volte ao Clareia para escrever o que aprendeu." },
];
