"use client";
import { useState } from "react";
import { englishCourse } from "./english-course-data";
import { conversationScenes, diagnosticQuestions, readingTexts, resourceLibrary, sentencePuzzles, soundPairs, writingProjects } from "./english-practice-data";
import { diagnosticAdvice, downloadText, exportPortfolio, learningStats, shuffled, wordCount, type DiagnosticState } from "./english-learning-tools";
import { isEnglishAnswer, readCell, scheduleReview, type ExerciseResult, type LearningCells, type ReviewState } from "./english-progress";
import { EnglishListen, EnglishRecorder } from "./english-audio";
import { Exercise } from "./english-exercise";
type Save = (key: string, value: unknown) => void;
type Props = { cells: LearningCells; save: Save; openLesson: (id: string) => void };

function CopyActivity({ text }: { text: string }) {
  const [message, setMessage] = useState("");
  return <details className="en-external"><summary>Levar esta atividade para meu chat · opcional</summary><p>Copie e cole no chat gratuito que você já usa. Nada é enviado automaticamente. Você pode fazer toda a prática aqui sem IA.</p><textarea aria-label="Mensagem para copiar" readOnly rows={6} value={text} onFocus={(e) => e.currentTarget.select()} /><button type="button" onClick={async () => { try { await navigator.clipboard.writeText(text); setMessage("Copiado. Confira e cole no seu chat quando quiser."); } catch { setMessage("Selecione a mensagem e copie manualmente."); } }}>Copiar atividade</button><p role="status">{message}</p></details>;
}

export function EnglishDiagnostic({ cells, save, openLesson }: Props) {
  const state = readCell<DiagnosticState>(cells, "diagnostic", { answers: [], finished: false, at: 0 });
  const advice = diagnosticAdvice(state.answers);
  function answer(index: number, value: string, at: number) { save("diagnostic", { ...state, answers: Array.from({ length: 12 }, (_, i) => i === index ? value : state.answers[i] ?? ""), at }); }
  return <section className="en-panel"><span className="en-kicker">POR ONDE COMEÇAR</span><h3>Um diagnóstico para orientar seu estudo</h3><p>12 questões de estrutura e leitura. Faça sem consultar. “Não sei” ajuda a encontrar seu ponto de partida. Este teste não avalia fala, escuta ou escrita livre e não certifica nível.</p>{state.finished ? <><div className="en-metric-grid">{advice.groups.map((group) => <article key={group.name}><strong>{group.correct}/{group.total}</strong><span>{group.name}</span></article>)}</div><p>Sugestão: retome a aula {advice.lesson}. Você continua livre para escolher qualquer aula.</p><div className="en-actions"><button className="en-primary" onClick={() => openLesson(`english-${String(advice.lesson).padStart(2, "0")}`)}>Abrir aula sugerida</button><button onClick={() => save("diagnostic", { answers: [], finished: false, at: Date.now() })}>Refazer diagnóstico</button></div><details><summary>Conferir minhas respostas e explicações</summary>{diagnosticQuestions.map((q, i) => <article className="en-review-line" key={q.prompt}><strong>{i + 1}. {q.prompt}</strong><p>{state.answers[i] === q.answer ? "✓ Acertou" : "Revisar"} · Sua resposta: {state.answers[i] === "__skip__" ? "Não sei" : state.answers[i]}<br />Resposta: {q.answer}. {q.why}</p><button onClick={() => openLesson(`english-${String(q.lesson).padStart(2, "0")}`)}>Estudar este assunto</button></article>)}</details></> : <><p>{state.answers.filter(Boolean).length}/12 respondidas · seu andamento fica salvo</p>{diagnosticQuestions.map((q, i) => <fieldset className="en-diagnostic-question" key={q.prompt}><legend>{i + 1}. {q.prompt}</legend>{[...q.options, "__skip__"].map((option) => <label className="en-option" key={option}><input type="radio" name={`diagnostic-${i}`} checked={state.answers[i] === option} onChange={() => answer(i, option, Date.now())} /><span>{option === "__skip__" ? "Não sei ainda" : option}</span></label>)}</fieldset>)}<button className="en-primary" disabled={state.answers.length !== 12 || state.answers.some((v) => !v)} onClick={() => save("diagnostic", { ...state, finished: true, at: Date.now() })}>Ver meu ponto de partida</button></>}</section>;
}

export function EnglishProgressPanel({ cells, save, openLesson }: Props) {
  const [diagnostic, setDiagnostic] = useState(false);
  const stats = learningStats(cells);
  const complete = englishCourse.filter((lesson) => readCell(cells, `${lesson.id}:complete`, false)).length;
  const drafts = englishCourse.filter((lesson) => readCell(cells, `${lesson.id}:draft`, "").trim()).length;
  return <><section className="en-panel"><span className="en-kicker">PROGRESSO QUE VOCÊ CONSEGUE CONFERIR</span><h3>Seu percurso de inglês</h3><div className="en-metric-grid"><article><strong>{complete}/{englishCourse.length}</strong><span>aulas concluídas</span></article><article><strong>{drafts}</strong><span>aulas com produção</span></article><article><strong>{stats.mistakes.length}</strong><span>itens para reforçar</span></article></div><p>Os indicadores abaixo mostram respostas a exercícios. Escrita e pronúncia não recebem nota automática.</p><div className="en-table-wrap"><table><thead><tr><th>Habilidade</th><th>Itens tentados</th><th>Corretos agora</th><th>Sem apoio na primeira tentativa</th></tr></thead><tbody>{["Estrutura", "Vocabulário", "Leitura", "Escuta"].map((name) => { const group = stats.groups[name] ?? { attempts: 0, correct: 0, independent: 0 }; return <tr key={name}><th scope="row">{name}</th><td>{group.attempts}</td><td>{group.correct}</td><td>{group.independent}</td></tr>; })}</tbody></table></div><small>Na escuta, abrir a transcrição conta como apoio. Esses números não são uma nota de proficiência.</small><div className="en-actions"><button onClick={() => setDiagnostic(!diagnostic)}>{diagnostic ? "Fechar diagnóstico" : "Fazer / consultar diagnóstico"}</button><button onClick={() => downloadText(exportPortfolio(cells), "clareia-meu-portfolio.txt")}>Baixar meu portfólio</button></div></section>{diagnostic && <EnglishDiagnostic cells={cells} save={save} openLesson={openLesson} />}</>;
}

export function EnglishWeek({ cells, save, openLesson }: Props) {
  const [today] = useState(() => new Date());
  const start = new Date(today); start.setDate(start.getDate() - ((start.getDay() + 6) % 7));
  const key = `${start.getFullYear()}-${String(start.getMonth() + 1).padStart(2, "0")}-${String(start.getDate()).padStart(2, "0")}`;
  const stored = readCell<{ start: string; done: number[] }>(cells, "weekly", { start: key, done: [] });
  const done = stored.start === key ? stored.done : [];
  const diagnosis = readCell<DiagnosticState | null>(cells, "diagnostic", null);
  const stats = learningStats(cells);
  const suggested = stats.mistakes[0]?.lessonId ?? (diagnosis?.finished ? `english-${String(diagnosticAdvice(diagnosis.answers).lesson).padStart(2, "0")}` : englishCourse.find((lesson) => !readCell(cells, `${lesson.id}:complete`, false))?.id ?? "english-01");
  const titles = ["Avançar uma etapa da aula", "Revisar expressões e criar frases", "Ouvir e fazer um ditado", "Ler e justificar uma resposta", "Escrever e revisar um parágrafo", "Conversar e ouvir sua gravação", "Rever dificuldades ou descansar"];
  return <section className="en-panel"><span className="en-kicker">SEMANA DE {start.toLocaleDateString("pt-BR")}</span><h3>Um roteiro flexível</h3><p>Distribua as atividades conforme sua rotina. Marcar um dia registra sua autoavaliação; não gera pontos nem bloqueia aulas.</p><div className="en-week">{titles.map((title, i) => <label className="en-check" key={title}><input type="checkbox" checked={done.includes(i)} onChange={() => save("weekly", { start: key, done: done.includes(i) ? done.filter((d) => d !== i) : [...done, i] })} /><span><strong>{["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"][i]}</strong> · {title}</span></label>)}</div><button onClick={() => openLesson(suggested)}>Abrir minha prioridade →</button><small>A prioridade considera os itens a reforçar, o diagnóstico quando concluído e a próxima aula disponível.</small></section>;
}

export function WordTrainer({ cells, save }: { cells: LearningCells; save: Save }) {
  const [show, setShow] = useState(false);
  const [index, setIndex] = useState(0);
  const [sentence, setSentence] = useState("");
  const [message, setMessage] = useState("");
  const [now] = useState(() => Date.now());
  const cards = englishCourse.flatMap((lesson) => lesson.content.vocabulary.map((word, i) => ({ ...word, key: `word-review:${lesson.id}:${i}`, lesson })).filter((word) => readCell<string[]>(cells, `${lesson.id}:words`, []).includes(word.english))).sort((a, b) => readCell<ReviewState>(cells, a.key, { due: 0, stage: 0, last: 0 }).due - readCell<ReviewState>(cells, b.key, { due: 0, stage: 0, last: 0 }).due);
  const card = cards[index % Math.max(cards.length, 1)];
  if (!card) return null;
  const previous = readCell<(ReviewState & { sentence: string }) | null>(cells, card.key, null);
  const due = !previous || previous.due <= now;
  function rate(remembered: boolean) { save(card.key, { ...scheduleReview(previous, remembered), sentence: sentence.trim() || previous?.sentence || "" }); setMessage(remembered ? "Lembrança registrada. A próxima data foi atualizada quando a revisão estava vencida." : "Tudo bem precisar rever. Esta expressão volta em um dia."); setShow(false); setSentence(""); setIndex(0); }
  return <section className="en-panel"><span className="en-kicker">CARTÕES COM REVISÃO INDIVIDUAL</span><h3>Tente lembrar antes de revelar</h3><p>{cards.length} expressões guardadas · {due ? "Esta expressão está pronta para revisar" : `Próxima revisão: ${new Date(previous!.due).toLocaleDateString("pt-BR")}`}</p><div className="en-flashcard"><strong lang="en">{card.english}</strong><button onClick={() => setShow(!show)}>{show ? "Ocultar" : "Revelar significado"}</button>{show && <p>{card.portuguese}</p>}</div><label className="en-field">Uma frase minha com a expressão (opcional)<input lang="en" maxLength={300} value={sentence} placeholder={previous?.sentence || "Use uma situação fictícia"} onChange={(e) => setSentence(e.target.value)} /></label><div className="en-actions"><button disabled={!show} onClick={() => rate(false)}>Preciso rever</button><button className="en-primary" disabled={!show} onClick={() => rate(true)}>Lembrei antes de revelar</button><button onClick={() => { setIndex(index + 1); setShow(false); setSentence(""); setMessage(""); }}>Outro cartão →</button></div><small>Autoavaliação, sem correção da frase. Intervalos de 1, 3, 7, 14 e 30 dias; repetir antes do prazo não aumenta o intervalo.</small>{message && <p role="status">{message}</p>}</section>;
}

function Dictation({ cells, save }: Props) {
  const saved = readCell(cells, "lab-dictation", { index: 0, answer: "", correct: false, assisted: false });
  const [revealed, setRevealed] = useState(false);
  const [checked, setChecked] = useState(false);
  const lesson = englishCourse[saved.index % englishCourse.length];
  const text = lesson.expansion.passage.split(/(?<=[.!?])\s+/)[0];
  function update(value: Partial<typeof saved>) { save("lab-dictation", { ...saved, ...value }); }
  return <section className="en-panel"><h3>Ditado com comparação de texto</h3><p>Ouça e escreva a primeira frase de um texto da trilha. O resultado compara palavras; não avalia sua pronúncia.</p><label className="en-field">Trecho da aula<select value={saved.index} onChange={(e) => { update({ index: Number(e.target.value), answer: "", correct: false, assisted: false }); setRevealed(false); setChecked(false); }}>{englishCourse.map((item, i) => <option key={item.id} value={i}>{item.number}. {item.title}</option>)}</select></label><EnglishListen key={lesson.id} text={text} label="Ouvir a frase do ditado" /><label className="en-field">O que ouvi<input lang="en" value={saved.answer} maxLength={500} onChange={(e) => { update({ answer: e.target.value, correct: false }); setChecked(false); }} /></label><div className="en-actions"><button className="en-primary" disabled={!saved.answer.trim()} onClick={() => { update({ correct: isEnglishAnswer(saved.answer, [text]) }); setChecked(true); }}>Comparar</button><button onClick={() => { setRevealed(true); update({ assisted: true }); }}>Ver texto / usar como leitura</button></div>{checked && <div className="en-feedback" role="status"><strong>{saved.correct ? "A frase corresponde ao texto." : "Há diferenças. Compare e tente novamente."}</strong>{!saved.correct && <p>Confira contrações, palavras pequenas e a ordem. Caixa e pontuação final não alteram o resultado.</p>}</div>}{revealed && <p className="en-example" lang="en">{text}</p>}<CopyActivity text={`Estou praticando ditado em inglês. Use inglês britânico e ritmo devagar quando houver voz. Crie três frases curtas sobre ${lesson.title}, uma por vez. Se este chat não tiver áudio, transforme em completar lacunas. Espere minha resposta, explique a diferença e não atribua nota de pronúncia.`} /></section>;
}

function SentenceOrder({ cells, save }: Props) {
  const saved = readCell(cells, "lab-order", { index: 0, answer: "", correct: false, assisted: false });
  const target = sentencePuzzles[saved.index % sentencePuzzles.length];
  const [picked, setPicked] = useState<number[]>([]);
  const [show, setShow] = useState(false);
  const words = shuffled(target.split(" ").map((text, id) => ({ text, id })), saved.index + 51);
  const sentence = picked.map((id) => words.find((word) => word.id === id)!.text).join(" ");
  return <section className="en-panel"><h3>Monte a frase</h3><p>Toque nas palavras em ordem. Para retirar a última, use “Desfazer”.</p><div className="en-token-row">{words.map((word) => <button key={word.id} disabled={picked.includes(word.id)} lang="en" onClick={() => setPicked([...picked, word.id])}>{word.text}</button>)}</div><p className="en-example" lang="en" aria-live="polite">{sentence || "Sua frase aparecerá aqui."}</p><div className="en-actions"><button disabled={!picked.length} onClick={() => setPicked(picked.slice(0, -1))}>Desfazer</button><button disabled={picked.length !== words.length} className="en-primary" onClick={() => { save("lab-order", { ...saved, answer: sentence, correct: isEnglishAnswer(sentence, [target]) }); setShow(true); }}>Conferir</button><button onClick={() => { save("lab-order", { index: (saved.index + 1) % sentencePuzzles.length, answer: "", correct: false, assisted: false }); setPicked([]); setShow(false); }}>Outra frase →</button></div>{show && <p role="status">{saved.correct ? "✓ Ordem correta." : `Compare a ordem do sujeito, verbo e complementos: ${target}.`}</p>}<small>Algumas frases aceitam outras ordens em contexto. Este treino trabalha a sequência de referência exibida na correção.</small></section>;
}

function Conversation({ cells, save }: Props) {
  const [id, setId] = useState(conversationScenes[0].id);
  const [turn, setTurn] = useState(0);
  const scene = conversationScenes.find((item) => item.id === id)!;
  const stored = readCell<{ answers: string[] }>(cells, `conversation-${id}`, { answers: [] });
  const [model, setModel] = useState(false);
  return <section className="en-panel"><span className="en-kicker">CONVERSAÇÃO ROTEIRIZADA · SEM IA</span><h3>Ensaie uma situação real</h3><label className="en-field">Situação<select value={id} onChange={(e) => { setId(e.target.value); setTurn(0); setModel(false); }}>{conversationScenes.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.level}</option>)}</select></label><p>{scene.role}</p><span className="en-kicker">TURNO {turn + 1} DE {scene.turns.length}</span><p className="en-example" lang="en">{scene.turns[turn][0]}</p><EnglishListen key={`${id}-${turn}`} text={scene.turns[turn][0]} label="Ouvir a outra pessoa" /><p>{scene.turns[turn][1]}</p><label className="en-field">Minha resposta em inglês<textarea rows={3} maxLength={600} value={stored.answers[turn] ?? ""} onChange={(e) => save(`conversation-${id}`, { answers: Array.from({ length: 4 }, (_, i) => i === turn ? e.target.value : stored.answers[i] ?? "") })} /></label><button onClick={() => setModel(!model)}>{model ? "Ocultar exemplo" : "Ver uma resposta possível"}</button>{model && <p className="en-hint" lang="en">{scene.turns[turn][2]}</p>}<div className="en-actions"><button disabled={turn === 0} onClick={() => { setTurn(turn - 1); setModel(false); }}>← Voltar</button><button className="en-primary" disabled={turn === scene.turns.length - 1} onClick={() => { setTurn(turn + 1); setModel(false); }}>Próximo turno →</button></div><small>O roteiro não interpreta sua resposta. Confira se ela atende ao pedido, se faz sentido e se usa uma forma educada. Há várias respostas possíveis.</small><EnglishRecorder key={id} lessonId={`conversa-${id}`} /><CopyActivity text={`Quero ensaiar esta situação em inglês: ${scene.title}. Meu papel: ${scene.role} Faça uma pergunta de cada vez, espere minha resposta e adapte a próxima fala ao que eu disser. Explique uma melhoria em português, com gentileza e precisão. Priorize inglês britânico e ritmo devagar, caso use voz. Não solicite dados pessoais. Ao final, resuma três pontos para eu revisar. Não dê nota oficial.`} /></section>;
}

function Pronunciation() {
  const [index, setIndex] = useState(0); const item = soundPairs[index];
  return <section className="en-panel"><h3>Pronúncia: ouvir, perceber e repetir</h3><label className="en-field">Foco<select value={index} onChange={(e) => setIndex(Number(e.target.value))}>{soundPairs.map((pair, i) => <option key={pair.title} value={i}>{pair.title}</option>)}</select></label><p>{item.tip}</p><EnglishListen key={`pair-${index}`} text={item.words} label="Comparar os sons" /><p className="en-example" lang="en">{item.sentence}</p><EnglishListen key={`sentence-${index}`} text={item.sentence} label="Ouvir em uma frase" /><EnglishRecorder key={index} lessonId={`pronuncia-${index + 1}`} /><p className="en-note">Ouça a referência, repita acompanhando e depois tente sozinho. A voz sintética pode variar; consulte também os vídeos humanos em Materiais. Sua gravação não recebe nota.</p></section>;
}

function ReadingLab({ cells, save }: Props) {
  const [index, setIndex] = useState(0); const [translation, setTranslation] = useState(false); const [result, setResult] = useState<ExerciseResult>();
  const item = readingTexts[index];
  return <section className="en-panel"><span className="en-kicker">LEITURA PARA PROVAS E COTIDIANO</span><h3>Gênero, intenção e evidência</h3><p>Textos originais de prática Clareia, não questões oficiais do ENEM. Leia o enunciado e justifique sua escolha com uma pista do texto.</p><label className="en-field">Texto<select value={index} onChange={(e) => { setIndex(Number(e.target.value)); setTranslation(false); setResult(undefined); }}>{readingTexts.map((text, i) => <option key={text.id} value={i}>{text.genre} · {text.level}</option>)}</select></label><p className="en-reading-text" lang="en">{item.text}</p><button onClick={() => setTranslation(!translation)}>{translation ? "Ocultar tradução" : "Ver tradução"}</button>{translation && <p>{item.translation}</p>}<Exercise key={item.id} exercise={item.question} stored={result} assisted={translation} onResult={(next) => { setResult(next); save("lab-reading", { index, answer: next.answer, correct: next.correct, assisted: next.assisted }); }} /><small>{readCell(cells, "lab-reading", { index: -1 }).index === index ? "Última tentativa deste laboratório registrada." : ""}</small><p className="en-note">Antes de marcar, pergunte: qual alternativa é sustentada? Qual exagera, contradiz ou acrescenta algo que não foi informado?</p></section>;
}

function WritingLab({ cells, save }: Props) {
  const [id, setId] = useState(writingProjects[0].id); const project = writingProjects.find((item) => item.id === id)!;
  const value = readCell(cells, `project-${id}`, { draft: "", revision: "", checks: [false, false, false] });
  const count = wordCount(value.draft);
  return <section className="en-panel"><span className="en-kicker">OFICINA DE ESCRITA</span><h3>Planejar, escrever, revisar</h3><label className="en-field">Projeto<select value={id} onChange={(e) => setId(e.target.value)}>{writingProjects.map((item) => <option key={item.id} value={item.id}>{item.title} · {item.range}</option>)}</select></label><p>{project.brief}</p><label className="en-field">Primeira versão<textarea lang="en" rows={8} maxLength={1800} value={value.draft} onChange={(e) => save(`project-${id}`, { ...value, draft: e.target.value })} /></label><p>{count} palavras · referência: {project.range}. {count < project.min ? "Desenvolva as ideias para chegar à faixa proposta." : count > project.max ? "Revise repetições e detalhes desnecessários." : "O tamanho está na faixa proposta; confira agora o conteúdo."}</p><small>A contagem não avalia gramática, coerência ou qualidade do texto.</small>{project.checks.map((check, i) => <label className="en-check" key={check}><input type="checkbox" checked={value.checks[i]} onChange={(e) => save(`project-${id}`, { ...value, checks: value.checks.map((item, j) => i === j ? e.target.checked : item) })} />{check}</label>)}<label className="en-field">Segunda versão<textarea lang="en" rows={8} maxLength={1800} value={value.revision} onChange={(e) => save(`project-${id}`, { ...value, revision: e.target.value })} /></label><div className="en-actions"><button onClick={() => downloadText(`${project.title}\n\nRASCUNHO\n${value.draft}\n\nREVISÃO\n${value.revision}`, `clareia-projeto-${id}.txt`)}>Baixar minhas duas versões</button></div><CopyActivity text={`Estou praticando escrita em inglês. Tarefa: ${project.brief} Faixa proposta: ${project.range}. Peça meu texto e espere. Depois dê sugestões sobre clareza, organização, adequação à tarefa e gramática, explicando em português. Mostre um trecho por vez e peça que eu revise, sem escrever tudo por mim. Não atribua nota oficial. Meu texto não está incluído nesta mensagem; eu decido se vou compartilhá-lo.`} /></section>;
}

function MixedPractice({ cells, save, openLesson }: Props) {
  const [onlyMistakes, setOnlyMistakes] = useState(false);
  const state = readCell<{ ids: string[]; answers: string[]; finished: boolean }>(cells, "sprint", { ids: [], answers: [], finished: false });
  const all = englishCourse.flatMap((lesson) => [lesson.expansion.questions[0], lesson.expansion.transfer].map((question) => ({ lesson, question, id: `${lesson.id}:${question.id}` })));
  function start(seed: number) {
    const mistakes = learningStats(cells).mistakes.map((item) => `${item.lessonId}:${item.questionId}`);
    const eligible = all.filter((item) => onlyMistakes ? mistakes.includes(item.id) : !!cells[`${item.lesson.id}:step`] || !!cells[`${item.lesson.id}:complete`]);
    const selection = shuffled(eligible.length ? eligible : all.filter((item) => item.lesson.number <= 6), seed).slice(0, 6);
    save("sprint", { ids: selection.map((item) => item.id), answers: selection.map(() => ""), finished: false });
  }
  const items = state.ids.map((id) => all.find((item) => item.id === id)).filter((item) => !!item);
  const correct = items.filter((item, i) => isEnglishAnswer(state.answers[i] ?? "", item.question.answers)).length;
  return <section className="en-panel"><h3>Treino misto cumulativo</h3><p>Até seis questões de aulas abertas. Sem aula iniciada, usamos os fundamentos. O treino mistura conteúdos já disponíveis; não é uma prova inédita nem mede fluência.</p><label className="en-check"><input type="checkbox" checked={onlyMistakes} onChange={(e) => setOnlyMistakes(e.target.checked)} />Priorizar meus erros e acertos com apoio</label><button onClick={(event) => start(Math.floor(event.timeStamp))}>{items.length ? "Começar nova rodada" : "Montar minha rodada"}</button>{items.map((item, i) => <fieldset className="en-diagnostic-question" key={item.id}><legend>{i + 1}. {item.question.prompt}</legend>{item.question.options?.map((option) => <label className="en-option" key={option}><input type="radio" name={`sprint-${i}`} checked={state.answers[i] === option} disabled={state.finished} onChange={() => save("sprint", { ...state, answers: items.map((_, j) => i === j ? option : state.answers[j] ?? "") })} />{option}</label>)}{state.finished && <div className="en-feedback"><strong>{isEnglishAnswer(state.answers[i], item.question.answers) ? "✓ Correto" : "Revisar"}</strong><p>{item.question.explanation}</p><button onClick={() => openLesson(item.lesson.id)}>Voltar à aula {item.lesson.number}</button></div>}</fieldset>)}{items.length > 0 && <button className="en-primary" disabled={state.finished || state.answers.length !== items.length || state.answers.some((answer) => !answer)} onClick={() => save("sprint", { ...state, finished: true })}>Conferir rodada</button>}{state.finished && <p role="status">{correct}/{items.length} corretas nesta rodada. Retome as explicações dos itens que exigiram mais esforço.</p>}</section>;
}

function MistakePractice({ cells, save, openLesson }: Props) {
  const mistakes = learningStats(cells).mistakes;
  const [chosen, setChosen] = useState<string | null>(null);
  const [result, setResult] = useState<ExerciseResult>();
  const item = mistakes.find((item) => `${item.lessonId}:${item.questionId}` === chosen);
  const lesson = englishCourse.find((lesson) => lesson.id === item?.lessonId);
  const exercise = lesson && [...lesson.expansion.questions, lesson.expansion.transfer].find((q) => q.id === item?.questionId);
  return <section className="en-panel"><h3>Meu caderno de dificuldades</h3><p>Itens errados ou resolvidos com apoio. Uma retomada correta sem dica permite tirá-los desta fila; o histórico original fica preservado.</p>{!mistakes.length && <p>Não há itens pendentes nesta fila. Conforme você pratica, ela mostra o que precisa de reforço.</p>}{item && lesson && exercise ? <><button onClick={() => { setChosen(null); setResult(undefined); }}>← Ver fila</button>{exercise.skill === "Escuta" && <EnglishListen text={lesson.expansion.passage} />}<Exercise key={chosen} exercise={exercise} stored={result} onResult={setResult} /><div className="en-actions"><button disabled={!result?.correct || result.assisted} onClick={() => { save(`${lesson.id}:reinforced`, [...new Set([...readCell<string[]>(cells, `${lesson.id}:reinforced`, []), exercise.id])]); setChosen(null); setResult(undefined); }}>Marcar como reforçado</button><button onClick={() => openLesson(lesson.id)}>Rever explicação da aula</button></div></> : mistakes.map((entry) => <div className="en-review-line" key={`${entry.lessonId}:${entry.questionId}`}><div><strong>{entry.title}</strong><p>{entry.prompt}</p></div><button onClick={() => { setChosen(`${entry.lessonId}:${entry.questionId}`); setResult(undefined); }}>Praticar novamente</button></div>)}</section>;
}

export function EnglishPracticeHub(props: Props) {
  const [tool, setTool] = useState("mixed");
  const options = [["mixed", "Treino misto"], ["mistakes", "Minhas dificuldades"], ["dictation", "Ditado"], ["order", "Montar frases"], ["pronunciation", "Pronúncia"], ["conversation", "Conversação"], ["reading", "Leitura"], ["writing", "Escrita"]];
  return <><div className="en-section-heading"><div><span className="en-kicker">PRÁTICA POR HABILIDADE</span><h3>Laboratório de inglês</h3></div><label className="en-field">Quero treinar<select value={tool} onChange={(e) => { window.speechSynthesis?.cancel(); setTool(e.target.value); }}>{options.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div><div key={tool}>{tool === "mixed" && <MixedPractice {...props} />}{tool === "mistakes" && <MistakePractice {...props} />}{tool === "dictation" && <Dictation {...props} />}{tool === "order" && <SentenceOrder {...props} />}{tool === "pronunciation" && <Pronunciation />}{tool === "conversation" && <Conversation {...props} />}{tool === "reading" && <ReadingLab {...props} />}{tool === "writing" && <WritingLab {...props} />}</div></>;
}

export function EnglishMaterials() {
  const [skill, setSkill] = useState("Todas"); const [search, setSearch] = useState(""); const [level, setLevel] = useState("Todos");
  const resources = resourceLibrary.filter((item) => (skill === "Todas" || item.skill === skill || item.skill === "Todas") && (level === "Todos" || item.level === "Todos" || item.level === level) && `${item.title} ${item.task}`.toLowerCase().includes(search.toLowerCase()));
  return <section><span className="en-kicker">BIBLIOTECA GRATUITA</span><h3>Estude com as fontes originais</h3><p>Use os materiais gratuitos. Alguns sites também vendem serviços ou exigem conta para certas atividades; você não precisa comprar nada para concluir a trilha Clareia.</p><div className="en-two-col"><label className="en-field">Habilidade<select value={skill} onChange={(e) => setSkill(e.target.value)}>{["Todas", "Escuta", "Leitura", "Escrita", "Fala"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="en-field">Dificuldade<select value={level} onChange={(e) => setLevel(e.target.value)}>{["Todos", "Começando", "Ampliando", "Aprofundando"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="en-field">Buscar<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Vídeo, leitura, transcrição…" /></label></div><div className="en-lesson-grid">{resources.map((item) => <article className="en-lesson-card" key={item.url}><span className="en-kicker">{item.skill} · {item.level}</span><h4>{item.title}</h4><p>{item.task}</p><a href={item.url} target="_blank" rel="noopener noreferrer">Abrir fonte original ↗</a></article>)}</div>{!resources.length && <p>Nenhum material encontrado. Tente outro filtro.</p>}<p className="en-note">Para aprofundar, os níveis dos materiais externos ajudam a escolher a dificuldade. A Clareia não transforma a conclusão das 48 aulas em certificado A1, A2, B1, B2, C1 ou C2.</p></section>;
}
