// Generated by scripts/build-expanded-question-bank.mjs. Do not edit by hand.
import { portugueseQuestionChapters, portugueseQuestions } from "./question-bank-expansion-portuguese";
import { historyQuestionChapters, historyQuestions } from "./question-bank-expansion-history";
import { geographyQuestionChapters, geographyQuestions } from "./question-bank-expansion-geography";
import { philosophyQuestionChapters, philosophyQuestions } from "./question-bank-expansion-philosophy";
import { sociologyQuestionChapters, sociologyQuestions } from "./question-bank-expansion-sociology";
export const expandedQuestionChapters = [...portugueseQuestionChapters,...historyQuestionChapters,...geographyQuestionChapters,...philosophyQuestionChapters,...sociologyQuestionChapters];
export const expandedQuestions = [...portugueseQuestions,...historyQuestions,...geographyQuestions,...philosophyQuestions,...sociologyQuestions];
