"use client";

import { useState } from "react";
import { schoolSubjectMeta, subjectsForYear, topicsFor, yearLabel, type SchoolSubject, type SchoolYear } from "./school-data";

type Props = { year: SchoolYear; onOpenQuestions: () => void };

export default function SchoolCurriculum({ year, onOpenQuestions }: Props) {
  const subjects = subjectsForYear(year);
  const [active, setActive] = useState<SchoolSubject | null>(null);
  return <section className="grade-curriculum"><div className="grade-curriculum-hero"><div><span className="eyebrow">TRILHA PERSONALIZADA</span><h2>Conteúdo do {yearLabel(year)}</h2><p>As matérias, os conteúdos e as atividades abaixo pertencem à sua série. Ao mudar de ano, o painel reorganiza tudo automaticamente.</p></div><button className="primary" onClick={onOpenQuestions}>Resolver questões da série →</button></div><div className="grade-subject-grid">{subjects.map((subject) => { const meta = schoolSubjectMeta[subject]; const topics = topicsFor(year, subject); return <button key={subject} style={{ "--accent": meta.color } as React.CSSProperties} onClick={() => setActive(subject)}><span>{meta.icon}</span><div><small>{topics.length} UNIDADES · 100 QUESTÕES</small><h3>{meta.name}</h3><p>{topics.slice(0, 3).join(" · ")}…</p><div><i /><b>Abrir material →</b></div></div></button>; })}</div>{active && <div className="modal-backdrop grade-material-backdrop" role="presentation" onMouseDown={() => setActive(null)}><section className="grade-material-modal" role="dialog" aria-modal="true" onMouseDown={(event) => event.stopPropagation()} style={{ "--accent": schoolSubjectMeta[active].color } as React.CSSProperties}><button className="modal-close" onClick={() => setActive(null)}>×</button><header><span>{schoolSubjectMeta[active].icon}</span><div><small>{yearLabel(year)} · MATERIAL DA SÉRIE</small><h2>{schoolSubjectMeta[active].name}</h2><p>Estude as unidades na ordem e depois resolva o bloco correspondente de 10 atividades.</p></div></header><div className="grade-unit-list">{topicsFor(year, active).map((topic, index) => <article key={topic}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{topic}</strong><p>Aprenda o conceito, observe exemplos, registre um resumo e teste a aplicação em situações da sua série.</p></div><b>10 questões</b></article>)}</div><div className="grade-material-actions"><div><strong>Roteiro para cada unidade</strong><p>Teoria simples → exemplo resolvido → resumo próprio → 10 atividades.</p></div><button className="primary" onClick={() => { setActive(null); onOpenQuestions(); }}>Ir para as atividades →</button></div></section></div>}</section>;
}
