"use client";

import { useState } from "react";

type Props = { loading: boolean; onGoogleLogin: () => Promise<void> };

export default function StudentLobby({ loading, onGoogleLogin }: Props) {
  const [showPlus, setShowPlus] = useState(false);
  const scrollToAccess = () => document.getElementById("clareia-access")?.scrollIntoView({ behavior: "smooth", block: "center" });

  return <main className="student-lobby enem-lobby">
    <div className="lobby-glow lobby-glow-one" /><div className="lobby-glow lobby-glow-two" />
    <header className="lobby-brand"><img src="/clareia-logo.png" alt="Clareia — Estude com mais clareza." /><div className="lobby-brand-actions"><button type="button" onClick={() => setShowPlus(true)}>Conhecer o Plus</button><button type="button" className="lobby-login-link" onClick={scrollToAccess}>Entrar</button></div></header>
    <section className="lobby-shell welcome">
      <div className="lobby-story"><span className="lobby-pill">CLAREIA EDUCAÇÃO · FOCO NO ENEM</span><h1>Estude com mais clareza.</h1><p>Questões, simulados, provas do ENEM, organização e acompanhamento do seu progresso em um só lugar.</p><div className="lobby-steps"><article className="active"><span>01</span><div><strong>Aprenda</strong><small>Cronograma em ordem</small></div></article><article><span>02</span><div><strong>Pratique</strong><small>Questões reais do ENEM</small></div></article><article><span>03</span><div><strong>Meça</strong><small>Provas e simulados</small></div></article></div><div className="lobby-orbit" aria-hidden="true"><i /><i /><i /><span>LC</span><span>CN</span><span>MAT</span><b>E</b></div></div>
      <div className="lobby-card" id="clareia-access"><span className="eyebrow">ACESSO À PLATAFORMA</span><h2>Entre e continue de onde parou.</h2><p>O Google protege sua conta. No primeiro acesso, você confirma nome, nome de exibição e RA + dígito.</p>{loading ? <div className="lobby-wait"><span /><strong>Preparando seu acesso…</strong><small>Estamos conferindo sua conta com segurança.</small></div> : <button className="lobby-google" onClick={() => void onGoogleLogin()}><span>G</span><div><strong>Continuar com Google</strong><small>Progresso sincronizado</small></div><b>→</b></button>}<div className="lobby-security"><span>◆</span><p><strong>Identificação responsável.</strong> Pedimos somente Google, nome e RA + dígito. Sem série, data de nascimento ou e-mail institucional.</p></div><div className="lobby-enem-numbers"><span><strong>747</strong> habilidades</span><span><strong>2.000</strong> questões</span><span><strong>17</strong> provas internas</span></div></div>
    </section>
    <section className="lobby-public-section"><div><span className="lobby-pill">UMA PLATAFORMA, MAIS CLAREZA</span><h2>O que você precisa para avançar.</h2><p>O Clareia reúne a preparação em um caminho organizado, sem tirar o foco do que realmente importa: estudar.</p></div><div className="lobby-feature-grid"><article><strong>747</strong><span>habilidades organizadas</span></article><article><strong>2.000</strong><span>questões por matéria</span></article><article><strong>17</strong><span>edições em modo prova</span></article><article><strong>24</strong><span>aulas introdutórias de Inglês</span></article></div></section>
    <section className="lobby-plans"><div className="lobby-plans-heading"><span className="lobby-pill">CLAREIA FREE E PLUS</span><h2>Escolha como quer estudar.</h2><p>Uma apresentação comercial demonstrativa da Clareia Educação.</p></div><div className="plan-grid"><article className="plan-card"><span>Clareia Free</span><strong>R$ 0</strong><small>Para começar a organizar seus estudos.</small><ul><li>Plano de estudos ENEM</li><li>Questões, provas e simulados</li><li>Progresso sincronizado</li></ul><button type="button" className="secondary" onClick={scrollToAccess}>Começar a estudar</button></article><article className="plan-card plus"><b>DESTAQUE DA APRESENTAÇÃO</b><span>Clareia Plus</span><strong>R$ 119,90 <small>/ano</small></strong><small>Valor demonstrativo para o trabalho escolar.</small><ul><li>Experiência premium de estudos</li><li>Análises e organização avançadas</li><li>Ecobag exclusiva Clareia inclusa</li></ul><button type="button" className="primary" onClick={() => setShowPlus(true)}>Conhecer o Plus</button></article></div></section>
    <section className="lobby-ecobag"><div><span className="lobby-pill">OFERTA DO PLANO ANUAL</span><h2>Uma marca que acompanha sua jornada.</h2><p>No conceito do Clareia Plus anual, o estudante recebe uma ecobag exclusiva para levar cadernos, livros e materiais com a identidade da Clareia.</p><button type="button" className="secondary" onClick={() => setShowPlus(true)}>Ver proposta demonstrativa</button></div><img src="/clareia-ecobag.png" alt="Mockup demonstrativo da ecobag exclusiva Clareia" /></section>
    <footer className="lobby-footer"><span>Clareia Educação · Estude com mais clareza.</span><span>Apresentação comercial demonstrativa · Sem cobrança real</span></footer>
    {showPlus && <div className="plus-modal-backdrop" role="presentation" onMouseDown={() => setShowPlus(false)}><section className="plus-modal" role="dialog" aria-modal="true" aria-labelledby="plus-title" onMouseDown={(event) => event.stopPropagation()}><button type="button" className="plus-modal-close" aria-label="Fechar" onClick={() => setShowPlus(false)}>×</button><span className="lobby-pill">DEMONSTRAÇÃO COMERCIAL</span><h2 id="plus-title">Clareia Plus anual</h2><p>Uma experiência premium pensada para quem quer estudar com mais organização, foco e clareza.</p><div className="plus-modal-benefits"><span>✓ Recursos premium futuros</span><span>✓ Análises de desempenho</span><span>✓ Ecobag exclusiva inclusa</span></div><div className="plus-demo-note">Esta tela simula a próxima etapa da apresentação. Não há cobrança, checkout ou assinatura real.</div><button type="button" className="primary" onClick={() => setShowPlus(false)}>Voltar para o acesso</button></section></div>}
  </main>;
}
