#!/usr/bin/env python3
"""Extract the licensed SAME question text into a browser-friendly TypeScript file."""

from __future__ import annotations

import json
import re
from pathlib import Path

import pdfplumber


ROOT = Path(__file__).resolve().parents[1]
DATA_FILE = ROOT / "app" / "question-bank-data.ts"
PDF_FILE = ROOT / "public" / "materials" / "caderno-same.pdf"
OUTPUT_FILE = ROOT / "app" / "question-text-data.ts"


def read_questions() -> list[dict]:
    source = DATA_FILE.read_text(encoding="utf-8")
    raw = source.split("export const questions: Question[] = ", 1)[1].strip().removesuffix(";")
    return json.loads(raw)


def clean_text(value: str) -> str:
    value = value.replace("\u00ad", "").replace("\ufb01", "fi").replace("\ufb02", "fl")
    value = re.sub(r"[ \t]+", " ", value)
    value = re.sub(r"\n{3,}", "\n\n", value)
    return value.strip()


def main() -> None:
    questions = read_questions()
    extracted: dict[str, dict[str, object]] = {}
    visual_terms = re.compile(
        r"\b(imagem|figura|gr[aá]fico|tabela|mapa|esquema|ilustra[cç][aã]o|cart[aã]o|"
        r"diagrama|fotografia|charge|tirinha|quadro|representa[cç][aã]o|abaixo|acima)\b",
        re.IGNORECASE,
    )

    with pdfplumber.open(PDF_FILE) as pdf:
        for index, question in enumerate(questions, start=1):
            chunks: list[str] = []
            for segment in question["segments"]:
                page = pdf.pages[segment["page"] - 1]
                bbox = (
                    segment["x"],
                    segment["y"],
                    segment["x"] + segment["width"],
                    segment["y"] + segment["height"],
                )
                text = page.crop(bbox).extract_text(x_tolerance=2, y_tolerance=3) or ""
                if text.strip():
                    chunks.append(clean_text(text))
            combined = clean_text("\n".join(chunks))
            extracted[question["id"]] = {
                "text": combined,
                "needsVisual": bool(visual_terms.search(combined)) or len(combined) < 90,
            }
            if index % 100 == 0:
                print(f"Extracted {index}/{len(questions)}")

    payload = json.dumps(extracted, ensure_ascii=False, separators=(",", ":"))
    OUTPUT_FILE.write_text(
        "// Generated by scripts/build-question-text.py. Do not edit by hand.\n"
        "export type QuestionText = { text: string; needsVisual: boolean };\n"
        f"export const questionText: Record<string, QuestionText> = {payload};\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT_FILE} ({OUTPUT_FILE.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
